### ISSUE TITLE
布局是否能选择锚点？

### ISSUE THREAD

**Issue by 169469** [enderneko/Cell#10]
现在锚点固定左上，向右下扩展，有些布局实现不了……比如以左下为锚点，向上扩展，实现单列的团队布局……

**Comment by 169469** [comment]
另外我看锚点好像固定所有布局都是同一个？这……

**Comment by enderneko** [comment]
考虑了下，很抱歉，暂时不打算加入自定义框架增长方向的功能。
因为要根据队伍的实时状况调整定位框体的大小，而这个框体是一个“SecureFrame”，在战斗中有人加入或离开队伍会导致框架错位。而且还涉及到宠物与NPC框架的锚点问题。
目前还有其他问题需要解决，所以这个需求只能先“搁置”了，也没法保证以后是否会有此功能。

**Comment by enderneko** [comment]
r25-release 已追加对锚点功能的支持。
