### ISSUE TITLE
Lua error: Cell/Indicators/Base.lua:239: attempt to compare number with nil

### ISSUE THREAD

**Issue by class2u** [enderneko/Cell#103]
您好! 感謝更新到 10.2.5! 

使用 r215-release 版本，點設定選項視窗上方的 "外觀" 標籤頁時會發生下面的 Lua 錯誤：

4x Cell/Indicators/Base.lua:239: attempt to compare number with nil
[string "@Cell/Indicators/Base.lua"]:239: in function `SetCooldown'
[string "@Cell/Modules/Appearance.lua"]:255: in function <Cell/Modules/Appearance.lua:253>
[string "=[C]"]: in function `Show'
[string "@Cell/Modules/Appearance.lua"]:1352: in function `onEventFunc'
[string "@Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Cell/Modules/OptionsFrame.lua"]:95: in function <Cell/Modules/OptionsFrame.lua:92>
[string "@Cell/Widgets/Widgets.lua"]:724: in function <Cell/Widgets/Widgets.lua:722>

Locals:
frame = CellAppearancePreviewIcon4 {
 BottomLeftCorner = Texture {
 }
 duration = FontString {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 ag = AnimationGroup {
 }
 textFrame = Frame {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 height = 22
 stack = FontString {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 ShowDuration = <function> defined @Cell/Indicators/Base.lua:421
 preview = Frame {
 }
 width = 22
 ShowAnimation = <function> defined @Cell/Indicators/Base.lua:430
 0 = <userdata>
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 ShowStack = <function> defined @Cell/Indicators/Base.lua:439
 SetCooldown = <function> defined @Cell/Indicators/Base.lua:217
 SetFont = <function> defined @Cell/Indicators/Base.lua:212
 UpdatePixelPerfect = <function> defined @Cell/Indicators/Base.lua:447
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 spark = Texture {
 }
 BottomEdge = Texture {
 }
 TopEdge = Texture {
 }
 icon = CellAppearancePreviewIcon4Icon {
 }
 cooldown = CellAppearancePreviewIcon4CooldownBar {
 }
 maskIcon = CellAppearancePreviewIcon4MaskIcon {
 }
 Center = Texture {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
start = 13266.360000
duration = 13
debuffType = nil
texture = 136085
count = 0
refreshing = nil
threshold = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
Cell = <table> {
 CreateTripleSwitch = <function> defined @Cell/Widgets/Widgets.lua:1318
 MIN_DEBUFFS_VERSION = 189
 CreateMask = <function> defined @Cell/Widgets/Widgets.lua:1640
 GetUnitFrame = <function> defined @Cell/Utils.lua:1887
 MIN_QUICKASSIST_VERSION = 213
 WrapTextInAccentColor = <function> defined @Cell/Widgets/Widgets.lua:162
 SetTooltips = <function> defined @Cell/Widgets/Widgets.lua:403
 CreateColorPicker = <function> defined @Cell/Widgets/Widgets.lua:846
 CreateBindingButton = <function> defined @Cell/Widgets/Widgets.lua:3037
 CreateScrollTextFrame = <function> defined @Cell/Widgets/Widgets.lua:2302
 funcs = <table> {
 }
 CreateStatusBarButton = <function> defined @Cell/Widgets/Widgets.lua:1569
 snippetVars = <table> {
 }
 patrons1 = <table> {
 }
 SetEnabled = <function> defined @Cell/Widgets/Widgets.lua:169
 MIN_CLICKCASTINGS_VERSION = 189
 CreateTipsButton = <function> defined @Cell/Widgets/Widgets.lua:734
 IndentationLib = <table> {
 }
 isRetail = true
 animations = <table> {
 }
 GetAccentColorTable = <function> defined @Cell/Widgets/Widgets.lua:146
 frames = <table> {
 }
 CreateTitledPane = <function> defined @Cell/Widgets/Widgets.lua:265
 CreateSlider = <function> defined @Cell/Widget

**Comment by enderneko** [comment]
已修复，感谢反馈。
