### ISSUE TITLE
Shaman showing in light (mage) blue?

### ISSUE THREAD

**Issue by Erieeroot** [enderneko/Cell#106]
Went into a follower dungeon to test party frame layout and it appears that shaman show in light blue like a mage instead of the traditional darker blue?  

Not sure if this is follower dungeon related or in general as I just got Cell, but seems unintentional either way.
![Screenshot 2024-05-06 190446](https://github.com/enderneko/Cell/assets/71171107/4ae3c6d6-450c-4742-9796-fd78b489983f)

**Comment by Erieeroot** [comment]
Confirmed it only does this in follower dungeons.... only a minor annoyance for content that most people will probably never do, but I will leave this up since it is technically still a bug :)...who knows, someone else may test the frames in there and see the same thing lol

**Comment by enderneko** [comment]
fixed, thanks!
https://github.com/enderneko/Cell/commit/0ed9f230e1a9379a31a8615f9f7e320d56295f22

**Comment by enderneko** [comment]
yea, blame blz
`UnitClassBase` returns wrong values
`UnitClass` works fine
