### ISSUE TITLE
[Feature request] Class color for health text

### ISSUE THREAD

**Issue by Redbrick09** [enderneko/Cell#107]
Name text in a player's frame can be configured to be either a static color or the color of the player's class, but health text can only be configured as a static color. It would be great if it were possible to set health text to class color as well so the two indicators can be consistent with each other. For example:

![image](https://github.com/enderneko/Cell/assets/169145175/70e28fb8-78a9-473f-be94-4741d8e631da)

vs

![image](https://github.com/enderneko/Cell/assets/169145175/bc727a86-5c61-4f7a-91dc-7c0626fd9d2e)

**Comment by enderneko** [comment]
sure, next version.

**Comment by enderneko** [comment]
implemented https://github.com/enderneko/Cell/commit/cea8b2e7e2f895599989436bede4b18c8951c4d5

**Comment by Redbrick09** [comment]
Thanks very much, can't wait to try it out!
