### ISSUE TITLE
Buggy Click-Castings

### ISSUE THREAD

**Issue by knoxsteady** [enderneko/Cell#11]
While trying to set up click-castings for spells, I ran into issues.
I was attempting to use keyboard buttons 1-0 as keybinds. When using 1-5, they bugged out and changed to mouse buttons (1 = left, 2 = right, 3 = middle, 4 = Mouse4, 5 = Mouse5). When I typed in a 1 and clicked Save at the bottom, it would auto-change to left, for example. Using other keyboard keys like 'Q' and 'E' worked fine. Upon trying to use keyboard button 6, I ran into other issues. When I typed in 6 and clicked Save at the bottom, it turned all custom keybinds invisible. I know they are invisible and not deleted because when I click 'New' enough times then it causes the window to scroll down, as if making room for more things that arent there.

**Comment by enderneko** [comment]
Confirmed, wrong regular expressions caused this issue.
Fixed! Thanks!
I'll release it later.
