### ISSUE TITLE
Request: Sort by Role per Group

### ISSUE THREAD

**Issue by PsjKana** [enderneko/Cell#115]
Currently Sort by Role only works in a 5man group.
For Raid environments you have to merge.

![image](https://github.com/enderneko/Cell/assets/46686174/f2838009-5451-4a45-a97d-01e0da1358f2)

Please provide an option to sort on a per group basis, to retain the group numberings and layouts

**Comment by atti92** [comment]
This feature is a must as a healer.

**Comment by enderneko** [comment]
Implemented
