### ISSUE TITLE
使用聖言術:庇 或治療禱言會跳出奇怪訊息

### ISSUE THREAD

**Issue by MorrisCom** [enderneko/Cell#12]
在團隊副本或者是戰場中那種多人副本 只要使用聖言術:庇 或治療禱言 每案一次就會跳一次奇怪的訊息
團隊中非常的影響操作 希望12/10打團本前解決這個問題
![螢幕擷取畫面 2020-12-01 221755](https://user-images.githubusercontent.com/57181186/100754398-060f4e00-3426-11eb-8cd9-32807721c85c.jpg)
![螢幕擷取畫面 2020-12-01 221857](https://user-images.githubusercontent.com/57181186/100754410-0871a800-3426-11eb-88b4-4de3987f0618.jpg)

**Comment by enderneko** [comment]
如果能附上完整的报错信息就更好了。
我稍后试试能否重现这个问题。

**Comment by MorrisCom** [comment]
他報錯的訊息有點長  好像只有跟別人組隊的時候會出現 我自己跑去副本裡面並不會跳出來 
只有前面七張是照順序 後面兩張時間來不及就隨便挑一段擷取了
![1](https://user-images.githubusercontent.com/57181186/100762083-8b96fc00-342e-11eb-83f6-96fa43e66090.jpg)
![2](https://user-images.githubusercontent.com/57181186/100762088-8d60bf80-342e-11eb-8372-b20fe5b9c6b9.jpg)
![3](https://user-images.githubusercontent.com/57181186/100762094-8e91ec80-342e-11eb-9d59-7a0f3743c747.jpg)
![4](https://user-images.githubusercontent.com/57181186/100762095-8f2a8300-342e-11eb-867a-84bccf5406e0.jpg)
![5](https://user-images.githubusercontent.com/57181186/100762097-8f2a8300-342e-11eb-97d9-b957e2175853.jpg)
![6](https://user-images.githubusercontent.com/57181186/100762098-8fc31980-342e-11eb-8086-4e8ee857457b.jpg)
![7](https://user-images.githubusercontent.com/57181186/100762103-905bb000-342e-11eb-9627-88d95afc9ff3.jpg)
![8](https://user-images.githubusercontent.com/57181186/100762105-90f44680-342e-11eb-9c80-f0be231086aa.jpg)
![9](https://user-images.githubusercontent.com/57181186/100762109-918cdd00-342e-11eb-990d-ead10fb61cde.jpg)

**Comment by MorrisCom** [comment]
我盡量照順序擷圖了 希望對你有幫助
![1](https://user-images.githubusercontent.com/57181186/100764687-956e2e80-3431-11eb-810c-a0a8d26d3a1f.jpg)
![2](https://user-images.githubusercontent.com/57181186/100764689-969f5b80-3431-11eb-8e66-8ada52b7c0ac.jpg)
![3](https://user-images.githubusercontent.com/57181186/100764692-9737f200-3431-11eb-9ae5-f40e8366ca50.jpg)
![4](https://user-images.githubusercontent.com/57181186/100764694-97d08880-3431-11eb-8771-e0b8d8ef06a4.jpg)
![5](https://user-images.githubusercontent.com/57181186/100764696-98691f00-3431-11eb-9299-a6abee61e6aa.jpg)
![6](https://user-images.githubusercontent.com/57181186/100764699-9901b580-3431-11eb-93c5-3afe5905b14d.jpg)
![7](https://user-images.githubusercontent.com/57181186/100764701-999a4c00-3431-11eb-9a41-934e77c5da0a.jpg)
![8](https://user-images.githubusercontent.com/57181186/100764703-9a32e280-3431-11eb-9817-90f43877b44e.jpg)
![9](https://user-images.githubusercontent.com/57181186/100764706-9a32e280-3431-11eb-8b83-2dd56eed278a.jpg)
![10](https://user-images.githubusercontent.com/57181186/100764711-9acb7900-3431-11eb-9f66-174f2945876a.jpg)
![11](https://user-images.githubusercontent.com/57181186/100764713-9b640f80-3431-11eb-92fb-83aebef1be8b.jpg)

**Comment by enderneko** [comment]
感谢反馈！ 已修复，马上发布，r28-release。
