### ISSUE TITLE
Changes to Dispels in Cataclysm

### ISSUE THREAD

**Issue by Phaugt** [enderneko/Cell#121]
[https://www.wowhead.com/news/changes-to-dispels-in-cataclysm-151398](https://www.wowhead.com/news/changes-to-dispels-in-cataclysm-151398)

As previously mentioned, we are providing three dispel capabilities to all healing classes as follows:
**Druids** will be able to dispel **defensive magic, curses, and poison.**
**Paladins** will be able to dispel **defensive magic, diseases, and poison.**
**Priests** will be able to dispel **defensive magic, offensive magic, and disease.**
**Shaman** will be able to dispel **defensive magic, offensive magic, and curses.**

Is this something that can be changed? Because it confuses me sometimes when playing rsham since it can't dispel poison or disease anymore.

**Comment by enderneko** [comment]
https://github.com/enderneko/Cell/commit/b033fbd2003ba013f3d29ed782bcfa052a32ac5e
already fixed >_<

**Comment by Phaugt** [comment]
so how does it work then? have had the issue since prepatch
is it something that could have been stored in my profile?


![image](https://github.com/enderneko/Cell/assets/41962737/739b1f29-008c-4de5-aa8b-fcead5dab18a)
![image](https://github.com/enderneko/Cell/assets/41962737/6d947511-3b85-4502-bac2-eca891979173)
![image](https://github.com/enderneko/Cell/assets/41962737/e753b957-205b-4a39-8cf9-5beff70648e8)

**Comment by Phaugt** [comment]
oh sorry - but then we done here! 

fixed in commit https://github.com/enderneko/Cell/commit/b033fbd2003ba013f3d29ed782bcfa052a32ac5e will come in future release.
