### ISSUE TITLE
Options on Spotlight Panel Hiding Behind Frames

### ISSUE THREAD

**Issue by elkewtf** [enderneko/Cell#127]
When attempting to setup what I would like the boxes in the upper row to be assigned to (focus for example) the dropdown options are hiding behind the panels and I'm unable to select the requisite option for those frames.

![image](https://github.com/enderneko/Cell/assets/51923252/7df4a646-aeae-410f-83f1-74ca7dc068e3)

**Comment by enderneko** [comment]
Fixed
