### ISSUE TITLE
[Feature Request] Status Text and Duration X-Offset

### ISSUE THREAD

**Issue by Ethereal-Seraphim** [enderneko/Cell#130]
Would it be possible to make is it so that Status Text Position and Duration are moveable on the x-axis. I think it would also be ideal if you could move them independent of each other.  Being able to move Both Status Text Position and the AFK/OFFLINE Timer would allow more flexibility in placement of other elements on the unit frame.

**Comment by enderneko** [comment]
sorry, but no such plan for now
