### ISSUE TITLE
[Bug] Deleting an indicator allows the user to create an invalid indicator

### ISSUE THREAD

**Issue by tomratford** [enderneko/Cell#133]
It seems that sometimes after deleting a indicator, when you go to create a new indicator you are able to create the indicator without a name. This then breaks the entirety of the indicator panel and required me to manually change the lua table with `/script` to remove the broken entries.

To reproduce:
* reload ui
* open cell -> indicators
* create two new indicators
* delete one of the indicators
* open the dialog to create a new indicator, then close it
* delete the second indicator
* open the dialog to create a new indicator. You should now be able to create a new indicator without a name.

---

<details><summary>Screenshot of 'create new indicator' panel with blank name but highlighted 'yes' button</summary>
<p>

![Screenshot 2024-06-15 at 15 03 29](https://github.com/enderneko/Cell/assets/42618982/eabaab45-2fe2-44c4-b9a3-400710d9ed69)

</p>
</details>

---

<details>
<summary>Bugsack output for broken indicator panel</summary>
<pre class="notranslate">
<code class="notranslate">
8x Cell/Modules/Indicators.lua:1983: attempt to index a nil value
[string "@Cell/Modules/Indicators.lua"]:1983: in function <Cell/Modules/Indicators.lua:1959>
[string "@Cell/Modules/Indicators.lua"]:1410: in function <Cell/Modules/Indicators.lua:1395>
[string "@Cell/Widgets/Widgets.lua"]:1801: in function <Cell/Widgets/Widgets.lua:1800>

Locals:
last = Button {
 BottomLeftCorner = Texture {
 }
 fs = FontString {
 }
 color = <table> {
 }
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 ShowTooltip = <function> defined @Cell/Modules/Indicators.lua:2000
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 height = 20
 hoverColor = <table> {
 }
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 HideTooltip = <function> defined @Cell/Modules/Indicators.lua:2009
 id = 31
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 typeIcon = Texture {
 }
 tooltips = <table> {
 }
 0 = <userdata>
 UpdatePixelPerfect = <function> defined @Cell/Widgets/Widgets.lua:674
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 _tooltipsInited = true
 SetTexture = <function> defined @Cell/Widgets/Widgets.lua:632
 TopEdge = Texture {
 }
 Center = Texture {
 }
 BottomRightCorner = Texture {
 }
 width = 20
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 BottomEdge = Texture {
 }
 SetTextColor = <function> defined @Cell/Widgets/Widgets.lua:568
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
}
(for control) = 32
i = 32
t = <table> {
 showDuration = false
 auras = <table> {
 }
 showAnimation = true
 showStack = true
 spacing = <table> {
 }
 indicatorName = "indicator3"
 size = <table> {
 }
 enabled = true
 type = "icons"
 frameLevel = 5
 auraType = "buff"
 castBy = "me"
 font = <table> {
 }
 name = ""
 position = <table> {
 }
 orientation = "right-to-left"
 trackByName = false
 numPerLine = 5
 num = 5
}
b = Button {
 BottomLeftCorner = Texture {
 }
 color = <table> {
 }
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @
 </code>
 </pre>
 </details>

**Comment by enderneko** [comment]
Fixed, thanks!
