### ISSUE TITLE
Click-Casting Spell shown as invalid

### ISSUE THREAD

**Issue by Alyeska70** [enderneko/Cell#136]
![grafik](https://github.com/enderneko/Cell/assets/32765997/2954e822-0981-43e4-91b4-b26ce6e90eb6)
![grafik](https://github.com/enderneko/Cell/assets/32765997/f4f3a97e-6c1f-44eb-9ae6-10f8a8acf040)
The spells are shown as invalid, however they work. This only for a few days though. I'm not sure, when it occured the first time. As I normaly don't switch speccs. 
Whenever I switch specs (eg back from Guardian to Resto), I need to reload the profile, or else the click-casting is not working. So I noticed, that the icons of the spells shown as invalid.

**Comment by enderneko** [comment]
rebind.
it's not a bug.
in r228, some click-casting issues were fixed, and caused this "issue".
