### ISSUE TITLE
[Feature] Add grouping/collapse feature to ANY type of indicator.

### ISSUE THREAD

**Issue by Pyrowar** [enderneko/Cell#138]
Currently only icon indicator can group in line (have max icons/icons per line changed) and have the ability to collapse - meaning when some indicator is no longer there, others update their place.

When working with multi-hot classes, it's a natural player preference to have texture indicators (instead of icons) and having this option would greatly improve space available at one time on the frame.

**Comment by enderneko** [comment]
just like "dynamic groups" in WA, right?
it's hard for current design.
requires lots of work/time to make that happen. 🤣
maybe it will be implemented someday, but not now, not on the priority list yet.
