### ISSUE TITLE
有關縮放大小

### ISSUE THREAD

**Issue by lohanchieh** [enderneko/Cell#15]
作者有考慮讓外觀中的縮放大小 150% 也弄成完美細緻模式嗎?(因為沒有完美細緻模式的邊邊會多出一些小黑框) 200%之後的有點會大了些 .. 100%的又有點小 ..

**Comment by enderneko** [comment]
很抱歉，缩放是通过调用SetScale实现的。
除非重写SetScale，否则无法实现。而且那样工作量太大，每个组件的大小都要设置多套尺寸。

**Comment by lohanchieh** [comment]
了解，謝謝作者的回覆，加油唷~
