### ISSUE TITLE
Duplicating a Layout

### ISSUE THREAD

**Issue by skulldir** [enderneko/Cell#153]
When setting up the addon for the first time I think that just about everyone will export + import their initial layout, and then modify.  I think that allowing a profile duplication would make this nicer.  I also think that allowing a imported profile to have a custom name would be better than forcing the previous name, or previous name + number

**Comment by enderneko** [comment]
![image](https://github.com/enderneko/Cell/assets/16433215/28e3bda8-e419-45ea-a78d-bc274842a571)
already there

**Comment by enderneko** [comment]
you can "Inherit" any existing layouts
