### ISSUE TITLE
Ability to turn off glow in Indicator Preview

### ISSUE THREAD

**Issue by skulldir** [enderneko/Cell#155]
A checkbox next to Scale slider and Show All check bow to turn on/off the glow that indicates what indicator you are looking at would be nice especially if you have show all unchecked because there is litterally only 1 group on top of your health bar.

**Comment by enderneko** [comment]
Implemented
https://github.com/enderneko/Cell/commit/5e641d4b924fd46361b4013444b0007413c49bcf
