### ISSUE TITLE
关于wlk版本真言术：盾监测的bug

### ISSUE THREAD

**Issue by yaoj-y** [enderneko/Cell#158]
使用5级的真言术盾时，不论是否装备盾的雕文，关于护盾条和护盾持续时间的监测都会出问题，具体表现就是
1.护盾条被添加后不会消失
2.真言术：盾的监测图标不会显示持续时间和护盾量，在灵魂虚弱的持续时间结束后图标会消失
等级1-4时没有问题，>5级是否有问题不清楚

**Comment by enderneko** [comment]
是的，5级的ID写错了，所以匹配不到。
已经改了，下版本生效。
