### ISSUE TITLE
[Feature Request] Disable "jump" when debuff/buff is applied/re-applied

### ISSUE THREAD

**Issue by Moonbloom** [enderneko/Cell#159]
Whenever a buff/debuff is applied/re-applied, the icon for it "jumps" a little
This is extremely distracting in a raid with loads of debuffs/buffs going

**Comment by enderneko** [comment]
![image](https://github.com/enderneko/Cell/assets/16433215/a8f892eb-2510-4185-ba66-78e6f1a7d19f)
