### ISSUE TITLE
关于队伍职责标识。

### ISSUE THREAD

**Issue by jsavage123** [enderneko/Cell#16]
1.在战斗中，队伍职责标识会不断闪动，整体看起来会让人分神，能否为此功能设置一个开关，不需要这个效果的时候可以关闭。
2.可驱散减益的图标目前为小骷髅，可否考虑做一个开关，显示为原deBuff图标，因为治疗偶尔会需要根据队友deBuff决定驱散的优先级。

PS:无论如何，感谢插件制作者的无私奉献。

**Comment by enderneko** [comment]
这些基本是已有的功能。
1. 那个是“仇恨指示器”，如不需要可以禁用。
2. “驱散”指示器不会改了，如需要显示能驱散的减益，修改“减益”指示器的“只显示我能驱散的减益”选项。
