### ISSUE TITLE
Spells Gone After Update and New Mini-Update.

### ISSUE THREAD

**Issue by Zalagar** [enderneko/Cell#160]
I updated to the newest version I think it was 2 days ago? After the update, none of my spells now show up on Cell. I'm a Resto Shaman and nothing shows up anymore besides debuffs. I can no longer see Earth Shield, Riptide, Ward of Faceless Ire, or anything else on cell and it's really frustrating as I have to watch all this stuff to play my spec. I saw they put out another update today and tried that, it didn't ![Screenshot 2024-07-07 020500](https://github.com/enderneko/Cell/assets/92698527/2996521d-d018-410b-9a01-b00a5f598c7b)

**Comment by Yassine1338** [comment]
If you just want the Defaults back type: /cell healers
