### ISSUE TITLE
Rescue doesn't work

### ISSUE THREAD

**Issue by Eressevoa** [enderneko/Cell#161]
Hey, since last update, Evoker rescue doesn't work on click casting. Used to work fine before. 

Tried :
- removing and adding it back to the spell list
- changed the binding
- Added the binding to my bars on the same thing

If you have questions feel free to ask

**Comment by enderneko** [comment]
[ClickCastings.zip](https://github.com/user-attachments/files/16123504/ClickCastings.zip)
overwrite this file `Cell\Modules\ClickCastings.lua`
