### ISSUE TITLE
[Bug] Indicator Color by Duration keeps resetting to % option

### ISSUE THREAD

**Issue by pandho** [enderneko/Cell#163]
Hello and thank you for your great addon!

I encountered a bug with the new version (Cell-r232-release):
After I switched the "Color By Duration" setting to "Stack" and back on a custom Block Indicator to test the new option, I cannot enable the "Remaining Time < X sec" setting. Instead the setting auto-resets to "Remaining Time < X%".

**Comment by enderneko** [comment]
"Duration" / "Stack"
you can only choose one.

**Comment by pandho** [comment]
Yes, but I cannot return to "Duration: Remaining Time < X sec".
![time](https://github.com/enderneko/Cell/assets/80176154/97414fcc-1706-4938-b4fb-6a11916cd1d6)
(This keeps automatically getting disabled.)

If I switch between "Duration" and "Stack" once, no matter what I click, it always resets to "Duration: Remainign Time < X %".
![percent](https://github.com/enderneko/Cell/assets/80176154/ad86c702-bf36-446c-a0de-bfaaf2cbc28f)
(I don't want to use this or Stack, but it is always active now.)
