### ISSUE TITLE
[Feature Request] Texture Selection for Shields and Heal Absorbs

### ISSUE THREAD

**Issue by LootFever** [enderneko/Cell#164]
An option to select the texture for Shields and Heal Absorbs would be nice,
instead of being forced into using those stripes.

Overall the options for those overlays (heal prediction, absorbs, shields etc.) feel quite limited.

**Comment by enderneko** [comment]
you can use this snippet https://github.com/enderneko/Cell/blob/master/.snippets/ShieldAndAbsorb_CustomTexture.lua

but this may not be added as an option
