### ISSUE TITLE
[Bug] Missing Stacks on some debuffs / always the first debuff misses the stacks

### ISSUE THREAD

**Issue by Sebastian1989101** [enderneko/Cell#166]
Even tho I setup show stacks on debuffs, on some debuffs it won't show the stacks. Tested it with Crawth's Deafening Screech (Algeth'ar Academy) and Melidrussa Chillworn's magic debuff from the adds (Ruby Life Pools), tank should have 5 stacks of crawth debuff here: https://i.imgur.com/OsReYJ3.png

**Comment by Sebastian1989101** [comment]
This is my current cell profile: 

`!CELL:232:ALL!vR1E4Xr11DpA1illdfzzByam4XgzJ9IFjzlzqbcz3vRLwzjTBxTYe7yIMz3Dwnt0SZmEMzTTmbOiWQesOiuPUPn9brH8GKsEOsiPjXjevcTKMeUiiHf3KgqyCiVijQKK28Q9CU3z2DKS5lo)t)(kFmRM79EUNx3Z9C)DUJ5U71ypSIHITS(D34yoQMhzatDtv7cY5vswYvYAvQA5vYyAQ7Qz5KWiMzXSYUQwRuw)iYJ6mOvEzxLovYwQqbhPzkQyukLPJMRMPXuUMwdL1011S4yU2Ygo6AW8A01Jv(KDGPIMmtMK91B89KXUtLcYL0DTZKmf2MBTtIAukzB3rLSwrqrgffOQ1kqTlQU2XoMSDEgDZwWwUOskBntBn3rTwJHPDrz9HCSmD11gw1DOdvsl3iYooAoUz1nZnIsEPPnpSITnWQE7ApQwRQKJsmDLsDRiR7QYKNnO6bLvAzT8sZPyiNvVI3rAUCLCaZnJYrDlzR40WyogAwwkUoxm3gTLl5AAxYqkAoZ8khTwPTUvr)HfZjBiMvrSGzjJ8IYUIQUUwoDS9Tpm4YkLDB5mlUDfJ8k2gkJyU9yk66B31wrz7fLDanB7BZNpna8e0DX1VDqqIiDDg9TD1(JE138BBh38nyOPlMwr3uo)Gj20MxVORPiOQkUIUQAo(AudiNYbMvEZJyi64oQoQC2IA5mn2o1PjQzKxlNmysoIBA97lE6mjIfP31VfX1hR3KX2763CdXI3BVdflzYE7m5n1)qdKz)9gx8geRskvgyyMOzjxXsgAUIzlbrlgIAfevTeTuSZPy4kE9IBYOuXSk2DiUJT2IhF3tKoJpuYbZmu3XJ0BMUhkv80XI3FgqaG9r5SC(8IoLkwe5hO1oOHoGRSBjhXe5Wo91FXnLfmufzJTaocxzW9yAOpQNCgyW(6lz)dLiwY(hyO49hjAVX7eesbzDhLg8D3okwY2qmI4r0Y7QkkdRHQkyOg1NXIjcipM64lvpbLoESmr6VRb7ns6HIn4aWgIHs0FNGJktY0mXVaXoiiwdim2ac1DelydcOtQY7SoXoLlkpSIyFkqSraJRFG8mYdV1w22oe11YAlB7BK9Ni2EZePRZP9zRue2BiAdH7GD6wYsmptomH6QQi6TJw0SaTjUZWFLCrgzgiAitIuGX2xY9fFO0rs05qdepZGPgQZ4zIKO3fAJznTHqEmUeStfhNowqqc6LrpPF0HNiIMmDNXtp0ajoagT1cBnkW08yAoijh4CUf7Tio8weZUfr5BDlINDyMh3ILS3KPb2Dl7ylIS)VLBLYzm7eZ3aBAeH9kaRXLe6wIUteR344oI(J0h(xiY0pQQ7K3eZ6tfpZqW2dqgirbcFX4QE1YIPGGuUfdSoAyASvwGQh3gCG4d1BIO4oHyj7RpFF4008CrO55Ay2C6qJyq(cnJHD2x2UhS)mXtp(DDGWHtdjjvAjRRmCoGlRvRqU7HhwxbtNpplRBg6WWK33ZDrJLxZbZ7LplKyc2GrA(0xeP5xhEURdqA(5UOWHjRLigMSoY6jBiqJthCKjXKS0Pl96b73AfofH84PvCkzBRKdpIG0S9nfjnMwzCYvTVtdYGSbsZpuJKMFu45bGNtFGoQYHoMeTHTc5UtN2XcscwFQx(rBmibKntcdDs2W5OZh6Cs5gLEGZz)xnP5O9fPR4JFhbn6RAF3bthVvsZ3oOHhaFEJ8k3AWb2O0ThSjW(0DMEWeDEINUNZs612X0ud1rvRGBAONN8pMSHhCvDa0fU(1)QDaKgo)ocpj4i2kDngMELgTcSzA6m9glSa3990DmvoxB9Q9mbxqIALs0tgGOwz6bnOzNW735lhKEOhb(Ffja97KQLv1IDMLDomJd7cg9KThKd7cL4(hoahqAo0R1rfoSR0fLZzBA1ilavmJTMXiWFBHXY2aY7ESGSe6ri0LFNbyj2d39VHQ8e7O2hE)pZpyXUsY2WvGTJRa(UhYozUas7mtJSBY12b56ywcPds4t)iDqEtmLMC9KBG8M7GCJmLIeLjhYvNLHr5zp7fVasChElrvfT)6rfDyxSLasBEo(3qLI6uFJuR3INhIeXZXurrVQcUqO8tZIT)6KMFgsZplPz3dCUInjBLk7V()x5e3OA2uPteFGmJ38c3Pc6r(Bf2swlKNyvnY09NamJMPTphKUHZUVN4aNd62OuTNRPd7zNppfqCuD5CJOdH3p4LvV44c1CORqi0RuJqiZRT(x6wQ)LENcCx3Cc1USFMa)p)QecTHUeQ5384c8YTkWBftG)hUuHqVLVJqOwkkW)W3MqD359lW9f3KqD1ShH6U5Tku31aTh4NkW)PxTa3h)mc8p)JB1yovzJHbWDqkEnLJOKFg7w3zRWPfWjhaiLgRGbjLTYHbc2yANCY6k8245yr01vTLPjCD6iC9choCtr6ivODSTDfIdcN(WjX2HWoAH(d03dNk86JTZocfIlnccWPajK6SiVIk76QRa5WvNoVcuUqAfltB3WQREA0VKbeZik29OoRUcUR0CR2iAPina7LThXPhv1SqDdQdP2Wm2kY5hnIr(uL017rDAxaz9qStYddNJtlw4IAys6jD4HBnmdnHFALdvsXX9e2m855vTD1kQaWmxnWqOqadhLmW(81xujlLENWJp9W6MhjPf16dN2s7Ok6hRhWWcXXTYu1UJT1ABRGpkMCikc6WMoTe5R)Q7DsnNOL00DtyinjoumezbDMzrBLsdziHAwzOXgrz0JaWpCMlL5raGcjmkuYbK34KdgMCZhRhUqHcknYBNmercc5jYsKS0rj5WMiZSi5NmHba34WaUt4itvzBL8iUwpt4Denl43390SARsNORUZq044MFedaKYauBojGYvA2CQk5gjrH4hfctDKM1wXsF0yEa)LSASauMHFt6eS1LhfCKoBKm44rlkRzCMXCSKZbad2)sJ6ODmLWNE5L876TU05qSxoPuSb3sPIglFQIYhL9QZkMzyBZswdWiLBwalrwndLUWoDuN0gG7KeXQ1ruay8EZIWBIN2UZi4XTPZkBKt10MOnMLxDKHVRT8qx2uoqyw0rtdZfQPZwdQFqghCmO8oxi0xFsl01paONlBmSCUbu0lOonvr2dSiQyFpsE)3uvlW5bVYhJ8wLiV9XYIl0BvZykAjM9QCyf9qPPqjdpDoD4OSHOn6GTegIZALhwbqVQR0pwrQVI2kuDlx0cMgU9mxQmIdaLgl2VSTT5rU8P6Z0WmNkGSwrkkcKCsCMIybLK3zpzXsCINMCFCCZwr7qcgdjfjAECZh1d2pflR6K4oMBcllj8uEfub1gG63UB7drnkYDro(nqUNEiV7lXgk4xhwcKi370ELkXKCyY7QxoYet5q7e7Bo2U8CJGUoJ8QzPgUZjStUN90BI(J3tiugTCDSFdLURUtoqMf15yDgpgsBNlU)iXIfpvgOFAhTgY7pr7mEKZI2otNO)9MO)U8OLzzHcLEpXt0v)W2qV5ANkounfqwLEAnYE27Iyg9YgYazkSLQ6B4jJhEgwnCERU4gr0FT6O9BYCwSlkWFzI8UGvO3Zsa)LkTFS7SfWt4DNHvIbazdItzxEbS3ROL7OjT3dKItfKRAv5sEOQcJ8bbjnflZHVG0iABzjxizcwunT3pswMiiFuPc(86ETwHVgQc5)uHTZoKjSA0t9Q03uUvE9YcJ(KD2wpqgPqtwPeSqh23Vujcbt6Wm63f31VKkbj0Up(Qjhk8g2WjQ4mdrU3jXnNvM1fqUGqRbM1y42DSZPXx8UaLEYY87w7mHbS1SGCoLdgjF(KgohmU(HhmXbJzARCW(uYRjFq)7C5GzKngzBUdlB12FatcDpk20P16FatRZudGZzACDKv1TTkyXxXveWn1lCcgMSNzWJb79zzJp5AwcA4tPthhhEgA4G3nSjr5tHk8XQX04rHIXW81mUnXC0thP9WC3pfmP1TUXRoPMOfJtVVJnzbzUHYK9xRwkmFwxinS5ZNww3svMUjA3ufy8QXqb5fRyrFE9JwcYmwFbyg5jcWOdxHrZgzyiPbuqlKQzKn7feWHPxKXbIIDto(sHzDjxs1znT)SKzMqdWCOboSjjBJbxhk8Mxwvx2C(tHwY)MjtmnJwAtYNAPKJFrNi42n6H2WESbu1u0ZlI8KkOgqLdYnG9cDATs8(HgasvKeovH1TJAw2n(eq8thXmUigybNUHgNPIFJX7GR7B8vgK(FCeYQFYkAXQj32SuSqiOieCefnvedTI0JXKi3t47zg8E9e9UP0lH8xOsojFimpX9q(M0MA8Rzj08gWAw8JcbZgY6I(hI7a2uAwe4Z37swgKgyfkE0uHKwHui8ZGsUZs2ubVC01U5fONKuKNJQpEs9nwjwjORkgoAhwzbAru8gEjF7LH6qt59jPkfVap5uQ(YvAbYv9Cj33nT59XvrUxSVX7iEnIv0bu0K7dO7kitmJSUEabUCYPqKTTbcDRBnWUOlgZPigbGgdMqFWH4dtDkEHURBlqyO1QCbAyKeGcif(FAf0ayqgyox4JvXCwR1kPEzneojIif354izxGcfXPW85PJOJGyJoAFks2aPiuEP0r1vuYlLowjBSvFYdRLtkBktnhmk5ETzSKARNKCYTSeuhTzCZzwvicJEv4OiTZH3ZIHl4zFwq9U0l9xqoTk5fwgQTNA5wxcdcDLszgap5kxji)eyebccyEFAsnVLJRGTCWXwnS9(gbEBPGUa9H1100JDzxIiZXCOWHBPLWT12zWaUxie54BMCkPSS9X8ukqjFEe7ndnNLVO)zQqoa826cOlNKPZZ7VNoJPvxqLay63wAPAmWSPS1qO2IrGDeo(5q5Hqil2aS(p(oTAkqh(1tijrphSACSczEEMna68LgWei378SlYqjVidMUx46feAzvYXQK3BOxi0SEvUX6qIg5wnP2AHunbQydbs8nxlkT7DoVRljgGEdc1yg0f0gIAzwMq8h5LBVvlafl8JLeG1ZnVPPT63cTKxyP4cZ8Npli(rbZfdq5MhKQHlCoFLTIq(1zZHJuzGtjHrHO1SVkRb2ryfNsMGSx8I9uYhIcxc23sbAC5xoSo1NMJdKJvmAGfyG)yWnYKjMPiJa24VCHO9z6EtsRpsuPwtDt7rAmAD74wTOrnDJkT(OdiD3nbBeYMdkVm6OqjJqepfOiG)j3is2EL6eMEcwfu5TqtCrv90077NC8LpMmesGB5IIcHTRz1uVfZ9C27zyWsC8G6TMLeIAhVWkMcsqd1u1lGvF5PrU68G7S(78LfQ5fhhVIi4Hu)6F187qOgP7O(t2Ua)V6zf4F3VMa)h5Pe4VVDlWBOiW)LEob(tSxb(3xTc8pAbb(N4(f4NELc1vVOqDlDcb(74weQlY3xOUD91eQRnEbUN9njW99AqOMFSKqT)I9x)Z8MecP2Jqnr7sOM8VMqOlC)c1MDhc8)WhbE(WWZhfE(ycHUOVXJwF9t9bUkHA(LPe422NsG)tAE6RxG)upy9)etb(NRBb(VW0ZqbWYQaZ5UBCAaPFMU3B)4XuBKCmjYrLWBaoDIKP9BMksVraa9TZAsgvkD6KDnyCjY1ifTVK9V3Qdy7Dt8sKoPtEuPSd0nufz)ETAT)uXKiBscekmr2fJ7jLwtfpJezlv5v247l5E9gEujYvcrc(Fwr6HJwlLyV000AEByEeoxkiVPcIOgqgoNduLgw6zeN(GcNLi3cC8X7Sbyn92TwnoweBB86BkczJ9j5pbpY4438CaSNKvlNn8uqwyTJbBwK1HDMkUpwzUniXK(mw4xbnU3fFqLXFcFzUMXS13oioAcWkdJmVvdRC0ZKSw6y(FkljGtWCBa4RA1jhEvzEOlZxNII5whVm31Gchn9YCBHoTBRm3vdSdMgk(tct7H2ETn5nT9xMBtb02YCBwf5DzUWm545t8KbX8miD3HkYxNLtCxbJ7hwLCKoihLmk5yKBvLuIdMNgiOhy7UG(HyhFQdvMBJHbAb2U67UXYCxS3AAzUlX7ny5RmNq1fxi0PmNO3ABzUlVAatzU1u5T1IXkL5UYkS7kwqeszUllyJlfEw3tg0Exp4tVkviyHAUGPIwm6D9n5XQCfeK70)Mhy1oTq0e3nuvohT2WlN8EGZ8j)zbsNsUFYFEyYdWkhMmP6zvRpBkNOsT9K)sY7vL8bKi)vNG8xVO6IjVVf3XulUJ)2fvRo5VBXu83VOk0jpy1AXjV)aV)3SOzUWsXpRsIjFOGLCt(WKpc5bGIF)9uin5JfS(zY)amRhzbLmt(4q3FcYNke5tUGAHRwzhz6GL9s(hxq1UFEvAXUKhnyrUKpnTui60FSEiFgYNL8pr(Cb44xiaIeG8Vi5lT4Yajpo0)x(SR0JmtG66i)ZlU6RQLXr(kblAJ8KVX1Pr(xcuBg5F9SljJ8ubleJ8vp7kWi)Bq)FnOolOARZvPwKVEGkSiFdczzKNwnW0FgO3zHcKwyftbldzcs5ZZYqiFluwppRQh8y0tTCSeJfxxZeKVZ5ld)3rg(TPvWGOFGIvQYpPQ877EEwVc5)WF)76y8JvlcGehJQcSu)Ibl8G8s)ElYGmNefypm1FWckiG8dPoIFe5hdaHiNwI8ksKZir(EsKxvI89LcuiaYOxtcDzag6Zte)KFsvS(O9mb5NI(5ay7L8W2JChGrcy(QmHZlb8FIAdJ1Vo5NVyi7KFray6KFjGnN8F9gGeFcYV6CGeN8F7TG8E4yRW)AQcF(cXM8BcIQM8BbK0KFhK1FjQK)hPVf6BPmGIGMHM(3p(5YWgLkj5PbjsKjkZvZIqkxg2CbGKlZvBqeYVCHYClLc1Tmx9WZYGNgOiCXzWxfSmWX6QGygXvtraxMB5m0VL5Ua45cdZO8pI6qPIUm3fbWClZbN2UIZd4TL5AAHiBlZTQ)Foo2YCRCzKx4cTAK9vsIuY1CGJO5MdsQDLnefVAtaCW4ZIqWgsZWXv2iNszUTMMIzJmyuhtDtYGaAp8ZNXUA9DTdGGf0tlTHtrg)4wKbPW5gQ4O4v0cDpdTPxzAqBYrbeAihkZ1czWYCTI)StA7Dr)TnSJ2PVUBK(r)dK(n1a5AAGSLgiD2G1Qmz17Uh7GFUJh9gFU2Ns2YsbawcM7DF5wR2NoaalIhojukMIlxwhxa6PC2(I3zIb7BESUMaFrR9zTQ8E3gf9tS5bHvAE)E7ujNwrzDUjL9VUSX8hQcnPr)3GwQZTaw50rhCH4WZKOPCXZ5xQD2HJG3fAisc(P9RiM(L9OGbAH9BOjlucVcj8laPs)yPTw9N5g2wopIz3xiHWiFCODZrPD3H4MYSYDigwc0GqHMbG6x5c)iFqBx2Lnpf9wOf730Ui4)QmP0k4RkqLt6QZdl7jlKglHiI)14UR2YgK70pN7Cfnl5OG8GzryNx7c)P9Q3reUafAo8tfKYwbQUfvRoKuRWTXa9L5aWtHwOhyAqoDbXc4cT0K6MoomF6u0pkCf3gp403vBCCtlNlNV7c5wOUVXNzfR9c21x(HPsYA1OwejRJPD2eg4x0JsPkLXSjz1yGpd3q5LThHY92BF3CCtvD2OZOAo7qOj4Py06qz8AA67(FrpC5Q6pExmxLBfRHPYQnS3Tk1t9F6Rvi0hdsRSZzG)(j8(hdaw4pLXhUM2BklxtdZ1Kn1FtEfwBQnY6RDYzAVj7qS(ATPSS(((vPdgLJ89G2HQWN2jVkRT340Pg1W0qzHIBQkx1QZgjn3a5ZCz1VQHM0)oG97tOU1UpYR3WSm7077Ptrr(tBGS)vtoqRY66aKb6xK3Bh6XAkcfICeeCYAwYYjV9O4OKdgonedAO8o6HTbBx0VYnUtJ3QPfEJw4vV9osNc)670YfUU2Q(7oBnuLVnoCKhtrBil(VKbhfsxlMv9I)7UOfbU3FxWZ(fc1XkeQz(ofQ51VfHAETMecTKZiu7RSkb(iFsHAFPVIqT)O2fQDU7sGx4veQ90ze4THC7hQdHAFXxsGp8hxG)nxRqT)SFIqTNA5anBqGFfFviH)BwOUggtG)r(IWZBvG)ZVgb(t(Cc1DL3MqDx7RjuxU(GtjoMa)SWHdFgEb(h)ZbVJht9Ef4)Sq7h53jW)DNvG)x(IWXy)A453c88oGNrH37eOFDc8pV7yf0SDCtxYq9)9`

**Comment by enderneko** [comment]
can't reproduce this issue...

**Comment by Sebastian1989101** [comment]
@enderneko even with all Addons disabled, I have this exact issue with the configuration of cell posted above. See this video: https://youtu.be/n6FDuiZt7uE the "+Dmgtaken" debuff aka "Sonic Vulnerability" has no stack indicator for whatever reason. This issue exists with multiple debuffs for example Magic Debuff on 1. Boss RLP, Poisen in HOI from the Frogs, this one from Bird Boss in AA and so on. As a healer this is a big issue and I don't know why this is happening.

**Comment by Sebastian1989101** [comment]
@enderneko Wild guess, but is it possible that the first debuff, no matter which one this is, always misses the stack indicator? I know that a "1" would make not much sense in the indicator preview, but it would explain this issue to me.

**Comment by Sebastian1989101** [comment]
@enderneko alright found the issue. As I have guessed, the first debuff is always missing the stacks. 

If I add the Savage Peck from that boss to the "Big Debuffs" section (so that it moves on position 1 when applied), I can see the stacks of the other debuff. See: https://i.imgur.com/9AOzpyd.png 

So I have to re-title the issue to "First debuff misses stacks always".

**Comment by enderneko** [comment]
seems found the cause.
it's about the parent frame of duration/stack text.
will try to fix later.

**Comment by enderneko** [comment]
826fc6c3ba80090f21052b2f5f4534414f44ad19
should work
you can download it then replace `Cell\Indicators\Base.lua`

**Comment by Sebastian1989101** [comment]
Seems to work, at least on Crawth. Will test the other locations where I noticed this problem over the weekend as well but so far looks good.
