### ISSUE TITLE
[Feature] Add different types of progress animations to indicators

### ISSUE THREAD

**Issue by Pyrowar** [enderneko/Cell#167]
I'm in awe of recently added Blocks indicator that allows to group healing over time effects. Much appreciated.

But I still have a small comment about the indicators :)

Previously, block indicator (singular) had a "Swipe" animation (weakauras style). Is there a possibility of preserving such feature within the new Blocks indicator? Icon indicators could also benefit from such customization.

Currently there is only "top to bottom" type of progress animation hardcoded into the indicators themselves.

**Comment by enderneko** [comment]
seems you haven't read the changelog.
Introduced a var "CELL_COOLDOWN_STYLE" in code snippets.

**Comment by rodneycheung** [comment]
The way to use it is to type

CELL_COOLDOWN_STYLE = "CLOCK"

in a snippet.
