### ISSUE TITLE
wow war within mythic plus

### ISSUE THREAD

**Issue by wowanima** [enderneko/Cell#168]
![wowwarwithin mythicplus](https://github.com/enderneko/Cell/assets/175316103/97721d55-8f20-4c56-bc33-a684cc63f2e4)

I do not speak English well.
But I'll do my best to explain.

It works normally on all servers.

It works when I'm connected to a GO TO ELEVEN server and I'm in a big city.

But the moment I activate the stone to proceed with wow war within mythic plus
It does not work as shown in the attached screenshot.

It works stably everywhere but from the moment I activate wow war within mythic plus it gives me an error

The error occurs only in dungeons where wow war within mythic plus is enabled.

1. Enter the dungeon.
2. Activate Mythic.(wow war within mythic plus)
3. An error occurs.
4. This only happens on “WOW WAR WITHIN BETA GOTOELEVEN” servers.

**Comment by enderneko** [comment]
Fixed (39bab3f70e2bb488b7fbf95b8f7890ee37deb26f)
You can download this file https://github.com/enderneko/Cell/blob/master/Utilities/BattleRes.lua
then replace `Cell\Utilities\BattleRes.lua`
