### ISSUE TITLE
Fixed (39bab3f70e2bb488b7fbf95b8f7890ee37deb26f)

### ISSUE THREAD

**Issue by wowanima** [enderneko/Cell#170]
Fixed (39bab3f70e2bb488b7fbf95b8f7890ee37deb26f)
You can download this file https://github.com/enderneko/Cell/blob/master/Utilities/BattleRes.lua
then replace `Cell\Utilities\BattleRes.lua`

_Originally posted by @enderneko in https://github.com/enderneko/Cell/issues/168#issuecomment-2224327793_
            
![wowwarwithin mythicplus2](https://github.com/user-attachments/assets/22ad7abd-0b67-4a2e-b114-dbdab0a9d936)

**Comment by enderneko** [comment]
Try this https://github.com/enderneko/Cell/blob/30597d10ac102de769a2c10dc89dfb433e915d40/Utilities/BattleRes.lua

**Comment by wowanima** [comment]
thank you!
It works perfectly.

**Comment by wowanima** [comment]
thank you!
It works perfectly.
