### ISSUE TITLE
A player distance bug followed by loss of healing indicators

### ISSUE THREAD

**Issue by Gruzzwald** [enderneko/Cell#171]
The first error is that on my Death Knight, other players appeared to be permanently fixed to "far away", with the box faded as if they were NOT in the vicinity. No other character had this issue, even when using the same profile layout. I also checked multiple UI settings and disabled other addons; this error persisted only for my DK. I also had Blizzard party frames "unhidden" which correctly showed when players were close versus far away; which Cell did not do for this character. 

The only solution I had was to delete and reinstall Cell. 

However, now I do not have the Healer Indicators plugging that came with Cell during my first download.

**Comment by enderneko** [comment]
range check issue should've been fixed in latest release.
the "Healers" indicator is a custom indicator not a built-in one.
use `/cell healers`
