### ISSUE TITLE
This addon break LibGetFrame

### ISSUE THREAD

**Issue by mrbuds** [enderneko/Cell#172]
https://github.com/enderneko/Cell/blob/3900c7496b2462dc48d996fe42f1ad9a5779c794/Utils.lua#L2213 replace LibGetFrame functions

If you want to improve LibGetFrame you are free to contribute, but replacing functions like this is not acceptable. This is forcing me to take steps to not let your code break mine.

**Comment by enderneko** [comment]
Okay, if you got mad with this, I can remove this.
But I don't get it, what do you mean by "break"?
If people use this addon (Cell), they want these WA showing on correct frames, doesn't it?
If they don't, this feature can be turned off in Cell options.

I understand it's free to contribute.
In my opinion this is a addon-specific feature, should not be added to that Lib which provides a generic solution.

I'll remove this, and find a way around.
Or I fork your lib and embed it into Cell. (And make my changes.)

**Comment by enderneko** [comment]
And just to confirm, can I embed a modified version of LibGetFrame?
It that "legal"?

**Comment by enderneko** [comment]
since it's opensource, and with a GPL-2.0 license.

**Comment by enderneko** [comment]
Please show me the way.
I'm always prepared to listen.

**Comment by enderneko** [comment]
05a26c3a8f0d35aeb7856c5df92fd42d8e143201
removed.

**Comment by enderneko** [comment]
```lua
local function AddonWorkaround(frame)
  if C_AddOns.IsAddOnLoaded("ElvUI") then
    if frame and frame:GetName():find("^ElvUF_") and frame.Health then
      frame = frame.Health
    end
  elseif C_AddOns.IsAddOnLoaded("Cell") then
    -- TODO:
  end
  return frame
end
```
Is this okay?
If it's okay, I'll do it and create a PR later.

**Comment by enderneko** [comment]
https://github.com/enderneko/LibGetFrame/commit/3d63881370eb6610ba6088f030a1df3603dee2e1
how about this?
If it's okay, I'll do it in this way, then create a PR.

**Comment by enderneko** [comment]
Updated.
Will create a PR.
