### ISSUE TITLE
Lua Error: bad argument #2 to '?' (Usage: self:SetVertexColor(color [, a]))

### ISSUE THREAD

**Issue by class2u** [enderneko/Cell#178]
Hi, I got this error message when I click the Appearance tab in options panel. The version of Cell is r235-release. WoW version is 11.0.0.

4x bad argument #2 to '?' (Usage: self:SetVertexColor(color [, a]))
[string "=[C]"]: ?
[string "=[C]"]: in function `SetVertexColor'
[string "@Cell/Modules/Appearance.lua"]:422: in function <Cell/Modules/Appearance.lua:416>
[string "@Cell/Modules/Appearance.lua"]:533: in function <Cell/Modules/Appearance.lua:478>
[string "@Cell/Modules/Appearance.lua"]:1564: in function `onEventFunc'
[string "@Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Cell/Modules/OptionsFrame.lua"]:95: in function <Cell/Modules/OptionsFrame.lua:92>
[string "@Cell/Widgets/Widgets.lua"]:731: in function <Cell/Widgets/Widgets.lua:729>

Locals:
(*temporary) = "bad argument #2 to '?' (Usage: self:SetVertexColor(color [, a]))"

**Comment by enderneko** [comment]
already fixed with r236
