### ISSUE TITLE
1x Cell

### ISSUE THREAD

**Issue by lohanchieh** [enderneko/Cell#18]
1x Cell\OptionFrames\ClickCastings.lua:243: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Cell\OptionFrames\ClickCastings.lua"]:243: in function <Cell\OptionFrames\ClickCastings.lua:241>
[string "@Cell\OptionFrames\ClickCastings.lua"]:309: in function `onEventFunc'
[string "@Cell\Libs\CallbackHandler.lua"]:24: in function `Fire'
[string "@Cell\Core.lua"]:557: in function `?'
[string "@Cell\Core.lua"]:602: in function <Cell\Core.lua:601>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by lohanchieh** [comment]
這個錯誤是不是在還沒有學到其他專精會跳出來的滑鼠按鍵施法設定裡面呢?

**Comment by enderneko** [comment]
这个错误不应该出现，它应该是由配置文件错误引起的。
使用 /cell 命令，并尝试重置点击施法。

**Comment by lohanchieh** [comment]
我大概知道原因了.我當時奶德下線時.滑鼠按鍵師法那邊是處於專精狀態.而我新創角色奶薩時還是1等還未跑出專精(這時會跑出錯誤).而我再去奶德那邊切換成沒有專精設定在登入奶薩錯誤就沒出現了.但也有可能是配置問題.感謝大大提供那麼好的插件.加油加油.棒棒的!!!
