### ISSUE TITLE
Custom macros does not works

### ISSUE THREAD

**Issue by RENgOLD** [enderneko/Cell#182]
Custom macros does not works since version 232

https://github.com/user-attachments/assets/f5b450dd-7475-410d-b27c-0cf2290ae2ae

**Comment by enderneko** [comment]
seems fixed 4bb7f6140f3bade3a65e6585a58e7f68dd3b17b5
replace `Cell\Modules\ClickCastings.lua` and try again

**Comment by RENgOLD** [comment]
> seems fixed [4bb7f61](https://github.com/enderneko/Cell/commit/4bb7f6140f3bade3a65e6585a58e7f68dd3b17b5) replace `Cell\Modules\ClickCastings.lua` and try again

yes, works fine now, thank you
