### ISSUE TITLE
Error while in party

### ISSUE THREAD

**Issue by nunovivas** [enderneko/Cell#183]
`Message: Interface/AddOns/Cell/Utilities/DeathReport.lua:216: attempt to call global 'GetSpellLink' (a nil value)
Time: Sun Jul 28 09:33:00 2024
Count: 2
Stack: Interface/AddOns/Cell/Utilities/DeathReport.lua:216: attempt to call global 'GetSpellLink' (a nil value)
[string "=[C]"]: in function `GetSpellLink'
[string "@Interface/AddOns/Cell/Utilities/DeathReport.lua"]:216: in function `COMBAT_LOG_EVENT_UNFILTERED'
[string "@Interface/AddOns/Cell/Utilities/DeathReport.lua"]:241: in function <Interface/AddOns/Cell/Utilities/DeathReport.lua:239>

Locals: `

**Comment by enderneko** [comment]
Fixed c77cb115e9ec5f16fb04e6503ce37875e2e8a440
next release
