### ISSUE TITLE
STEELSERIES World Of Warcraft MMO Mouse: extra buttons not working 赛睿魔兽世界鼠标额外按键无效

### ISSUE THREAD

**Issue by deepseer** [enderneko/Cell#185]
STEELSERIES World Of Warcraft MMO Mouse: extra buttons not working
赛睿魔兽世界鼠标额外按键无效

11.0前夕版本刚上线时，有个bug导致鼠标额外按键在任何场合都无法被识别。此bug已于今天（2024/7/31）修复。然而，Cell插件似乎还是无法正常生效。
设置如图所示：
![屏幕截图 2024-07-31 212146](https://github.com/user-attachments/assets/29ce5ae7-8a9e-41ec-a15b-d90c2a514cdd)
结果：对框体按对应的侧键，无反应。
（其他未截图部分：电脑的赛睿驱动已设置为游戏内模式In-Game Mode，Advanced Interface Options内已打开魔兽世界专用鼠标侦测，vuhdo已经能正常识别此按键点击施法）

**Comment by enderneko** [comment]
应该已于237修复了
