### ISSUE TITLE
Indicators not working when entering/leaving M+

### ISSUE THREAD

**Issue by Pegoth** [enderneko/Cell#195]
All of the indicators disappear and don't reappear until /reload when I enter or leave a M+ group. It started happening with the latest version only: r238

No lua error appears in BugSack.

----

It might be some other addon, more testing required.

**Comment by enderneko** [comment]
can't reproduce this issue.
could you share your config file?
`WTF\Account\YOUR_ACCOUNT\SavedVariables\Cell.lua`

**Comment by Pegoth** [comment]
You can safely ignore this issue for now, because I'm still testing it. I'll add more info when I conclude the tests or close if it was my other addons that caused the bug.

**Comment by Pegoth** [comment]
Okay it seems like a crude script I used to use centered anchor for Cell caused the issue, I removed it and now everything works as expected. It is weird, because it worked without an issue before, but I can live without it.
