### ISSUE TITLE
Interface Raid Profiles causes a lua error.

### ISSUE THREAD

**Issue by fireymerlin** [enderneko/Cell#2]
2x ...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:484: Usage: GetRaidProfileOption("profile", "optionName")
[string "=[C]"]: in function `GetRaidProfileOption'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:484: in function `initFunction'
[string "@SharedXML\UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:472: in function `CompactUnitFrameProfilesDropdown_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:29: in function `InterfaceOptionsList_DisplayPanel'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:47: in function `InterfaceOptionsListButton_OnClick'

**Comment by enderneko** [comment]
Fixed, and will be released soon.
