### ISSUE TITLE
r50版本安装以后卡bug，求大大帮助

### ISSUE THREAD

**Issue by Bigonionduck** [enderneko/Cell#23]
前俩天看到cell除出版本了，立刻就从curseforge上更新了，然后上游戏就出bug了。
先是团队框架血条有一半被白色覆盖了，然后不能通过点选框架来选定目标。
然后里面的指示器全部消失了，我一开始以为是重置了要重新设置，结果设置一个以后又全部出现，但不能修改，点击也没有具体内容。
最后就是副本减益那块里面什么都没有，还重叠了。

尝试了重装cell，删除后wtf里的配置文件重装都没有用，也不知道具体是什么原因，求作者大大帮助啊！T.T

**Comment by enderneko** [comment]
我这边在不同的电脑上都试过了，没有出现此类问题。
尝试过重置，一切正常。
附上报错信息。以及再次确认使用的版本。

**Comment by Bigonionduck** [comment]
我也不知道怎么给你看报错内容，只能游戏内给你截图了。

**Comment by Bigonionduck** [comment]
求大大帮助啊，我先是删了addons里面的cell文件包，然后重下没有用。然后我朋友说把wtf里账号里的cell相关文件也删掉，然后照做以后全部重新下载还是不行。最后重新下载r49版本，结果也不行了。
我又舍不得自己好不容易设好的这些指示器还有习惯，所以求大大帮忙看看有可能是因为什么？

**Comment by Bigonionduck** [comment]
我刚发现，我是通过邮件收到你的回复的，邮件里我附带上了我游戏内插件bug的截图，但是到这边截图就没有了

**Comment by Bigonionduck** [comment]
大大，能给个邮箱吗？我把图片发过去？或者这里有什么办法可以附带图片的吗？

**Comment by enderneko** [comment]
嗯，看了报错信息才好确定问题所在。
不过需要注意的是，从r50降回r49而不重置的话，是肯定有问题的。

**Comment by enderneko** [comment]
嗯，看了报错信息才好确定问题所在。
不过需要注意的是，从r50降回r49而不重置的话，是肯定有问题的。

**Comment by Bigonionduck** [comment]
可我插件这边并没有显示报错，就是除了问题，我游戏内没法使用而已。

**Comment by enderneko** [comment]
把截图拖进这个文本框就行。

**Comment by Bigonionduck** [comment]
好！
![版本](https://user-images.githubusercontent.com/83529143/116810980-d1a6d780-ab14-11eb-9f34-02ee4363bdf2.PNG)
![减益部分重叠并且没有详细内容](https://user-images.githubusercontent.com/83529143/116810983-d2d80480-ab14-11eb-9715-0234b064dc6c.PNG)
![随机创建即可还原但没有详细内容](https://user-images.githubusercontent.com/83529143/116810985-d4093180-ab14-11eb-9667-aaa908a3709a.PNG)
![指示器空白](https://user-images.githubusercontent.com/83529143/116810987-d53a5e80-ab14-11eb-8fe0-6d650b44928d.PNG)
![下半部分被白色遮住](https://user-images.githubusercontent.com/83529143/116811028-09158400-ab15-11eb-95fd-dc36c22cd2b1.PNG)

**Comment by enderneko** [comment]
嗯，这必然有报错的。确认版本是r50么？

**Comment by Bigonionduck** [comment]
第一个是版本；第二个是副本减益那一块重叠了，而且没有具体内容；第4个是指示器全部消失；第三个是点击创建以后之前的又出现了，最后一个就是框架下半部分被白色遮住了

**Comment by Bigonionduck** [comment]
真的没有啊，我当时更新完以后上线看到变成了最后图片那样，我还以为是外观材质那里变了，然后我就去修改，意外发现并没有变，然后接下来和朋友打本的时候指示器什么的都没有效果，而且框架没法点选才发现除了问题的。

**Comment by enderneko** [comment]
从这些现象是没法确认问题所在的，一定要知道报错的代码才行。
确认魔兽的lua报错是否开启。
开启是 /console scriptErrors 1
关闭是 /console scriptErrors 0
重载界面后看看是否有弹出报错窗口。

**Comment by Bigonionduck** [comment]
有了！
有17个，大大，请稍等，我一个个复制下来

**Comment by Bigonionduck** [comment]
Message: (null)
Time: Sun May  2 07:11:39 2021
Count: 3
Message: Error loading Interface\AddOns\LibDFramework-1.0\Libs\LibStub\LibStub.lua
Time: Sun May  2 07:11:39 2021
Count: 4
Message: Error loading Interface\AddOns\LibDFramework-1.0\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua
Time: Sun May  2 07:11:39 2021
Count: 4
Message: Couldn't open Interface\AddOns\LibDFramework-1.0\Libs\LibSharedMedia-3.0\lib.xml
Time: Sun May  2 07:11:39 2021
Count: 4
Message: Couldn't open Interface\AddOns\LibDFramework-1.0\Libs\AceGUI-3.0\AceGUI-3.0.xml
Time: Sun May  2 07:11:39 2021
Count: 4
还有好多，但我看了下都是LibDFramework-1.0\Libs\下的东西报错
最后一个是
Message: Error loading Interface\AddOns\LibDFramework-1.0\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua
Time: Sun May  2 07:11:39 2021
Count: 4

**Comment by enderneko** [comment]
很奇怪了，Cell并不使用LibDFramework。
通常这个是Details内置的，如果单独安装了LibDFramework，尝试在插件列表禁用看看。

**Comment by enderneko** [comment]
或者先锁定Cell的问题，将其他插件禁用。看看是否报错。也可能是兼容性问题。

**Comment by Bigonionduck** [comment]
行，我刚才把文件夹里的LibDFramework相关文件都已经删除了，重登了游戏
然后就只有这个报错
Message: (null)
Time: Sun May  2 07:20:50 2021
Count: 3
我现在将其他插件全部禁用，然后只留cell试试

**Comment by Bigonionduck** [comment]
Message: [string "MiDKP3MainFrame:OnLoad"]:10: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Sun May  2 07:23:31 2021
Count: 1
Stack: [string "MiDKP3MainFrame:OnLoad"]:10: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "*:OnLoad"]:10: in function <[string "*:OnLoad"]:1>

然后报错俩个
第一个
Locals: self = MiDKP3MainFrame {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = MiDKP3MainFrame {
 0 = <userdata>
}
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
第二个
Message: Interface\AddOns\Cell\Utils.lua:177: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Sun May  2 07:23:31 2021
Count: 1
Stack: Interface\AddOns\Cell\Utils.lua:177: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `ipairs'
[string "@Interface\AddOns\Cell\Utils.lua"]:177: in function `ConvertTable'
[string "@Interface\AddOns\Cell\RaidFrame\UnitButton.lua"]:103: in function `onEventFunc'
[string "@Interface\AddOns\Cell\Libs\CallbackHandler.lua"]:24: in function `Fire'
[string "@Interface\AddOns\Cell\Core.lua"]:69: in function `UpdateLayout'
[string "@Interface\AddOns\Cell\Core.lua"]:100: in function `onEventFunc'
[string "@Interface\AddOns\Cell\Libs\CallbackHandler.lua"]:24: in function `Fire'
[string "@Interface\AddOns\Cell\Core.lua"]:580: in function `GROUP_ROSTER_UPDATE'
[string "@Interface\AddOns\Cell\Core.lua"]:636: in function `?'
[string "@Interface\AddOns\Cell\Core.lua"]:692: in function <Interface\AddOns\Cell\Core.lua:691>

Locals:

**Comment by enderneko** [comment]
嗯，截图下你的指示器列表，内置的那些，我需要确定下它们的顺序。

**Comment by Bigonionduck** [comment]
![1](https://user-images.githubusercontent.com/83529143/116811548-08cab800-ab18-11eb-8cbd-5d5c2ff09bd7.PNG)
![2](https://user-images.githubusercontent.com/83529143/116811549-09fbe500-ab18-11eb-8570-93921c8b1a59.PNG)

**Comment by Bigonionduck** [comment]
那17和1都不是，是出bug以后我创建随便选的

**Comment by enderneko** [comment]
不是这些哦，是内置的“状态图标”、“减益”和“目标计数”。主要这三个是r50有改动的。
从报错信息得知问题就出在它们上。

**Comment by Bigonionduck** [comment]
那这个我应该在什么地方去截图？

**Comment by enderneko** [comment]
要确认“减益”一定是第18个指示器。

**Comment by Bigonionduck** [comment]
他不是第十八个
![1](https://user-images.githubusercontent.com/83529143/116811721-c190f700-ab18-11eb-971b-3f3af1b9aa00.PNG)
![2](https://user-images.githubusercontent.com/83529143/116811722-c2c22400-ab18-11eb-9589-e159a645a032.PNG)

**Comment by enderneko** [comment]
![Snipaste_2021-05-02_19-33-05](https://user-images.githubusercontent.com/16433215/116811708-3e55bc80-ab7d-11eb-9299-076c0cd33f1f.png)
 就是确认下你的指示器列表里是否有重复的“内置”指示器。以及“减益”是否是第18个，“目标计数”是最后一个。

**Comment by Bigonionduck** [comment]
嗯，有重复的护盾条，而且目标计数不是最后一个，减益也不是第18个

**Comment by enderneko** [comment]
嗯，问题已经确定了。
应该不是Cell的代码问题，但很奇怪你的指示器有很多重复的，顺序也不对……
这个需要修改你的配置文件。

**Comment by Bigonionduck** [comment]
那这个我该怎么办？不会需要全部重置吧，不要啊！这里面的指示器我设置了好久好久的，有没有办法不改我后面加入的，直接修改内置的配置文件的办法？

**Comment by enderneko** [comment]
把你的配置文件发过来，然后我给你修复下。

**Comment by Bigonionduck** [comment]
大大，配置文件在什么地方？

**Comment by enderneko** [comment]
wow\_retail_\WTF\Account\账号\SavedVariables\Cell.lua

**Comment by Bigonionduck** [comment]
[cell.zip](https://github.com/enderneko/Cell/files/6411245/cell.zip)

**Comment by Bigonionduck** [comment]
大大，那我同账户下的其他角色的cell文件也需要修改吗？还是只用改这一个就可以了

**Comment by enderneko** [comment]
不是这个哟

**Comment by enderneko** [comment]
WTF\Account\账号\SavedVariables\Cell.lua
不用进入服务器-角色文件夹

**Comment by enderneko** [comment]
改的是Cell账号通用配置，如果你有其他子账号，那么也可能要改。
如果只有这个账号，那么一个就够了。

**Comment by enderneko** [comment]
比如我的路径是 WTF\Account\150703635#4\SavedVariables\Cell.lua

**Comment by Bigonionduck** [comment]
[cell.zip](https://github.com/enderneko/Cell/files/6411253/cell.zip)

**Comment by Bigonionduck** [comment]
里面有俩个，反正我都打包发了，应该这次不会错了，大大你说的子账号是指的账号下的角色还是wow2这样的？

**Comment by enderneko** [comment]
[Cell.zip](https://github.com/enderneko/Cell/files/6411350/Cell.zip)
眼睛看花了……试试吧

**Comment by Bigonionduck** [comment]
哇！感谢大大！辛苦了！！！T.T

**Comment by enderneko** [comment]
记得要大退游戏再覆盖。

**Comment by Bigonionduck** [comment]
可以了！！！大大！！！超级感谢啊！只是变得好小啊！

**Comment by Bigonionduck** [comment]
已经重新调整大小了！！！大大，真的超级感谢你！！！

**Comment by Bigonionduck** [comment]
大大，最后还有俩个小的建议。
一个是我看到也有别人提的，就是能显示buff/debuff的具体信息，如果悬停在上面。
另一个是那个中了debuff的高亮驱散能不能只改成高亮边框？因为整体高亮我很容易看不清框架里的血量。

当然如果很麻烦，不好修改也没关系，我真的很喜欢cell这个插件，感谢大大啊！

**Comment by enderneko** [comment]
r50缩小了驱散高亮，但想要边框高亮那种效果的话可能还要等等，目前要修复窗口缩放的问题。
至于debuff的鼠标提示，现在是有一个占位的选项，不过这个优先级我放在了最后，修复完了已知的问题后，会添加。

**Comment by Bigonionduck** [comment]
好的，那辛苦大大了！
所以现在这个窗口缩放以后还会还原？那我是不是其实不要调整他的宽和高比较好？

**Comment by enderneko** [comment]
不是的，关于这个“尺寸、位置和以前版本不一样了”，其实是因为前49个版本都用了不正确的分辨率来缩放Cell。
r50算是修复了这个一直以来都没发现的问题。
目前要修复的“缩放问题”指的是准备添加更具体的缩放比例选项（或者做成滑动条、文本框），而不是现在的100% 150%之类的。另外就是使Cell无论在何种缩放比例下都能“像素精确”地显示。
总之，尺寸什么的还是得改了，虽然比较抱歉，但也不能一直使用错误的值了。

**Comment by Bigonionduck** [comment]
关于大大说的这个49个版本都用了不正确的分辨率来缩放Cell，前天我cell出问题的时候，我当时特意看了nga和更新的补丁，所以理解了。感谢大大的辛苦修复。我去修改尺寸不麻烦。
但是大大说的缩放问题现在的100%和150%我并没有在设置中找到这个，这个是指的什么？

**Comment by Bigonionduck** [comment]
看到了！在外观那个缩放页面，理解大大说的意思了！
那大大加油！！感谢大大啦！

**Comment by Bigonionduck** [comment]
大大！还得麻烦你一下！刚发现还有一个问题，就是关于指示器这块，我每设置一个新的指示器，它都需要在我布局下重新设置一次。
就是说比如我布局有4个：小队，战场15，战场40和团队四种。然后我新建了个恢复的指示器，然后我4个布局文件下都要建立一次同样的指示器以及调整位置，这样很麻烦。
有没有可能性只用建立一个通用的指示器，然后它会自动根据我在不同的布局里去对应位置和大小而不用一次次的去重建呢？

**Comment by enderneko** [comment]
每个玩家的不同布局的按钮尺寸都不尽相同，长宽比例也不一致，这种情况下难以统一缩放。
而且可能不是每个玩家都需要在不同的布局下同时创建同一功能的指示器……
所以，针对这个需求，解决方案就是“提供复制指示器到其他布局的功能”，但至于何时能实现么，再等等吧。

**Comment by Bigonionduck** [comment]
嗯，好的，了解了！
那再次感谢大大帮我解决了我的插件问题，辛苦大大了！
