### ISSUE TITLE
戰復計時器不會顯示

### ISSUE THREAD

**Issue by class2u** [enderneko/Cell#24]
你好! 我昨天使用 r51 版本打 M+ 時，戰復計時器的位子只有一個長方形的底色，但裡面內容是空的，沒有顯示任何文字數字。設定選項裡面確定有啟用戰復計時器。r52 版本則還沒有測試。麻煩你了！

**Comment by enderneko** [comment]
r54已修复。

**Comment by class2u** [comment]
十分感謝！
