### ISSUE TITLE
指示器 血量文字 會有錯誤

### ISSUE THREAD

**Issue by lohanchieh** [enderneko/Cell#28]
1x ...ceCell\Widgets\Widgets_IndicatorSettings.lua:1005: Usage: <unnamed>:SetValue(value, [treatAsMouseEvent])
[string "=[C]"]: in function `SetValue'
[string "@Cell\Widgets\Widgets_IndicatorSettings.lua"]:1005: in function `SetDBValue'
[string "@Cell\OptionFrames\Indicators.lua"]:973: in function <Cell\OptionFrames\Indicators.lua:894>
[string "@Cell\Widgets\Widgets.lua"]:740: in function <Cell\Widgets\Widgets.lua:738>

Locals:
(*temporary) = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 high = 50
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 lowText = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 highText = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 UpdateMinMaxValues = <function> defined @Cell\Widgets\Widgets.lua:1123
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 low = -50
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 onEnter = <function> defined @Cell\Widgets\Widgets.lua:1030
 currentEditBox = <unnamed> {
 }
 PixelSnapDisabled = true
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 TopRightCorner = <unnamed> {
 }
 afterValueChangedFn = <function> defined @Cell\Widgets\Widgets_IndicatorSettings.lua:991
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 onLeave = <function> defined @Cell\Widgets\Widgets.lua:1035
 TopEdge = <unnamed> {
 }
 0 = <userdata>
 SetName = <function> defined @Cell\Widgets\Widgets.lua:975
 Center = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 BottomEdge = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
}
(*temporary) = nil

**Comment by enderneko** [comment]
感谢反馈，已修复！将随下版本发布。
