### ISSUE TITLE
指示器里的技能能否用带颜色的点代替

### ISSUE THREAD

**Issue by omegabomb** [enderneko/Cell#29]
比如治疗关注的几个hot，可以自定义为红点，绿点，蓝点

**Comment by enderneko** [comment]
![rect](https://raw.githubusercontent.com/enderneko/ImageUpload/master/202204110151799.png)
目前没法设置圆点，只能创建“矩形”的自定指示器，并分别设置它们的尺寸颜色等（如果需要颜色不改变，就将时间颜色设置为相同）。
未来可能添加“材质”型指示器，到时方能添加各种形状的材质（如果有），但不保证。
