### ISSUE TITLE
触发型报错  好像是在跨阵营组队的时候就会触发

### ISSUE THREAD

**Issue by ChrnoChou** [enderneko/Cell#30]
19x Cell\Libs\LibGroupInfo-1.lua:173: attempt to index field '?' (a nil value)
[string "@Cell\Libs\LibGroupInfo-1.lua"]:173: in function <Cell\Libs\LibGroupInfo.lua:139>
[string "@Cell\Libs\LibGroupInfo-1.lua"]:187: in function <Cell\Libs\LibGroupInfo.lua:181>
[string "@Cell\Libs\LibGroupInfo-1.lua"]:285: in function `?'
[string "@Cell\Libs\LibGroupInfo-1.lua"]:122: in function <Cell\Libs\LibGroupInfo.lua:121>

Locals:
unit = "raid33"
guid = "Player-707-052F143E"
specId = 0
role = nil
(*temporary) = <table> {
 specRole = "RANGED"
 gender = "female"
 unit = "raid33"
 specIcon = 136186
 name = "曾经个也高"
 specName = "毁灭"
 specId = 0
 level = 60
 race = "人类"
 realm = "白银之手"
}
(*temporary) = nil
(*temporary) = 3
(*temporary) = 3
(*temporary) = "raid33"
(*temporary) = 3
(*temporary) = "attempt to index field '?' (a nil value)"
Print = <function> defined @Cell\Libs\LibGroupInfo.lua:22
UnitGUID = <function> defined =[C]:-1
cache = <table> {
 Player-804-051AA985 = <table> {
 }
 Player-1938-07CDB391 = <table> {
 }
 Player-877-0545C3F7 = <table> {
 }
 Player-826-01C698DF = <table> {
 }
 Player-886-05F66581 = <table> {
 }
 Player-916-03A74C6A = <table> {
 }
 Player-1933-025ABDFA = <table> {
 }
 Player-1955-028A8228 = <table> {
 }
 Player-736-04C0E9F8 = <table> {
 }
 Player-877-05204A96 = <table> {
 }
 Player-729-0623115B = <table> {
 }
 Player-745-041916CB = <table> {
 }
 Player-838-0261C784 = <table> {
 }
 Player-714-065C9F42 = <table> {
 }
 Player-891-025EDA92 = <table> {
 }
 Player-816-0343EC53 = <table> {
 }
 Player-916-0432885E = <table> {
 }
 Player-1695-006E3A5F = <table> {
 }
 Player-746-046506FA = <table> {
 }
 Player-707-066C638F = <table> {
 }
 Player-707-0666585F = <table> {
 }
 Player-804-03B797F2 = <table> {
 }
 Player-840-051B5DB4 = <table> {
 }
 Player-838-05623F37 = <table> {
 }
 Player-707-052F143E = <table> {
 }
 Player-714-0677BA7F = <table> {
 }
 Player-838-059706A7 = <table> {
 }
 Player-1939-06E7564D = <table> {
 }
 Player-723-060DBBF2 = <table> {
 }
 Player-916-038B3E2E = <table> {
 }
 Player-3751-06704A44 = <table> {
 }
 Player-916-03A4A0C1 = <table> {
 }
 Player-1939-07C8B529 = <table> {
 }
 Player-940-0551E53B = <table> {
 }
 Player-729-04041255 = <table> {
 }
 Player-1485-04B1352B = <table> {
 }
}
UnitIsUnit = <function> defined =[C]:-1
GetSpecialization = <function> defined =[C]:-1
GetSpecializationInfo = <function> defined =[C]:-1
GetInspectSpecialization = <function> defined =[C]:-1
UnitNameUnmodified = <function> defined =[C]:-1
GetNormalizedRealmName = <function> defined =[C]:-1
UnitLevel = <function> defined =[C]:-1
UnitRace = <function> defined =[C]:-1
genders = <table> {
 1 = "unknown"
 2 = "male"
 3 = "female"
}
UnitSex = <function> defined =[C]:-1
specData = <table> {
 62 = <table> {
 }
 63 = <table> {
 }
 250 = <table> {
 }
 251 = <table> {
 }
 252 = <table> {
 }
 253 = <table> {
 }
 254 = <table> {
 }
 255 = <table> {
 }
 256 = <table> {
 }
 257 = <table> {
 }
 258 = <table> {
 }
 259 = <table> {
 }
 260 = <table> {
 }
 261 = <table> {
 }
 262 = <table> {
 }
 263 = <table> {
 }
 264 = <table> {
 }
 265 = <table> {
 }
 266 = <table> {
 }
 267 = <table> {
 }
 268 = <table> {
 }
 269 = <table> {
 }
 270 = <table> {
 }
 70 = <table> {
 }
 102 = <table> {
 }
 71 = <table> {
 }
 103 = <table> {
 }
 72 = <table> {
 }
 104 = <table> {
 }
 73 = <table> {
 }
 581 = <table> {
 }
 105 = <table> {
 }
 577 = <table> {
 }
 64 = <table> {
 }
 66 = <table> {
 }
 65 = <table> {
 }
}
lib = <table> {
 specData = <table> {
 }
 cache = <table> {
 }
 callbacks = <table> {
 }
 specRoles = <table> {
 }
 RegisterCallback = <function> defined @ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterCallback = <function> defined @ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 queue = <table> {
 }
 order = <table> {
 }
 GetCachedInfo = <function> defined @Cell\Libs\LibGroupInfo.lua:32
 UnregisterAllCallbacks = <function> defined @ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
}
UPDATE_EVENT = "GroupInfo_Update"

**Comment by enderneko** [comment]
emmm，确实，我没试过跨阵营组队。
今晚我尝试修复下，感谢反馈！

**Comment by ChrnoChou** [comment]
感谢您的优秀插件才对  :-P

**Comment by enderneko** [comment]
前天改了下，不过忘记说了 _(:зゝ∠)_
https://github.com/enderneko/Cell/blob/master/Libs/LibGroupInfo.lua
需要手动替换下 Cell/Libs/LibGroupInfo.lua
下个版本的发布时间大概在9.2.7更新之后
