### ISSUE TITLE
减益添加只显示自身释放

### ISSUE THREAD

**Issue by pmzhudx** [enderneko/Cell#32]
是否可以为减益添加“只显示我施放的减益”选项？如同增益已有的“只显示我施放的增益”。

因为牧师使用“自定义减益”指示器监视虚弱灵魂时，也会显示其他牧师施加的虚弱灵魂。而不同牧师的虚弱灵魂不影响自身真言术：盾的释放，所以需要这一个选项屏蔽自身以外来源的减益。

非常感谢您贡献的优秀治疗框架

**Comment by enderneko** [comment]
是指“减益”指示器，还是“自定义”指示器？
这种情况可能需要特化处理，我看看有没有办法通过“代码片段”解决。

**Comment by pmzhudx** [comment]
![屏幕截图 2022-08-23 164445](https://user-images.githubusercontent.com/48729299/186114856-7a36b92b-c2e5-4af6-82f3-2f524f7688db.png)

应该是自定义指示器，如增益中加入“只显示我施放的增益”即可解决问题。

![屏幕截图 2022-08-23 165208](https://user-images.githubusercontent.com/48729299/186115941-38a33df8-51bd-40b6-bb84-812cd76b7ab2.png)

应该在所有治疗中只有虚弱灵魂会有“只显示我施放的减益”这个需求，可能代码片段是更好的处理方式，但是我不会写。只能烦请大大出手了。

感谢您的帮助。

**Comment by enderneko** [comment]
考虑之后，我选择将“不显示他人施加的虚弱灵魂debuff”内置。是牧师不在意别人的，不是牧师更不在意这个虚弱灵魂。
此改动，对“减益”和自定义指示器生效，但不影响“副本减益”指示器（没人会把虚弱灵魂添加到副本减益里吧）

[UnitButton.zip](https://github.com/enderneko/Cell/files/9413439/UnitButton.zip)
将这个压缩包中的 UnitButton.lua 替换 Cell\RaidFrame\UnitButton.lua。

距离下个版本的发布还有一段时间，正在做WLK的适配工作。
之后就不用手动替换了。

**Comment by pmzhudx** [comment]
感谢您的帮助，这确实是一个很小的细节，这样处理保持轻量化的同时也解决了问题。
