### ISSUE TITLE
Indicators > Dispels >Highlight unit button.

### ISSUE THREAD

**Issue by Jymitar** [enderneko/Cell#33]
It appears that the option to change the highlighting of dispels is broken. or not working properly. When you mouse over it it says "Show duration text" Also the change that you do there does not seem to persist(always return to default).

Attaching screenshot. 

![cellbug](https://user-images.githubusercontent.com/95532131/187102855-0a2c1a6e-7a87-4d2c-a164-00c167ff4d95.jpg)

The addon is awesome! Keep up the good work.

**Comment by enderneko** [comment]
Wrong tooltips should have been fixed. I'll release it soon.
Other than that, this checkbutton works fine.
