### ISSUE TITLE
希望可以開發經典服的Cell團隊框架

### ISSUE THREAD

**Issue by uli850817** [enderneko/Cell#35]
請問後續有考慮開發經典服的Cell團隊框架嗎?
在正服使用習慣，非常的喜歡~
很希望可以在經典服也能使用><

**Comment by uli850817** [comment]
好的那我明白了~非常感謝!!! 我去下載R109

**Comment by uli850817** [comment]
您好~昨天用都還正常，今天經典服有更新
剛才上線看都已經看不見名字，框架內容也無法調整
如附件



[
![1662171726236](https://user-images.githubusercontent.com/112614195/188252229-dc7822d3-fab1-4a18-aa3e-2527ee8b79d1.jpg)
](url)

**Comment by enderneko** [comment]
嗯，我看了下，今天的更新暴雪偷偷加了个 WOW_PROJECT_WRATH_CLASSIC。
导致之前的版本判断失效了。
马上发布。

**Comment by uli850817** [comment]
好的感謝~
