### ISSUE TITLE
玩WLK团本碰到的问题

### ISSUE THREAD

**Issue by eprendre** [enderneko/Cell#36]
今天看到了这个插件，感觉对治疗非常友好。基本上我在grid2里面折腾了半天的东西，这边全部开箱即用。但是发现在团队里无法显示宠物，我还以为是自己设置没摸清楚，去FAQ一看：
Q4：能不能隐藏宠物？
A4：单人不能，小队能，团队本身就没写宠物框架。

但是目前永恒之眼P3骑龙，以及NAXX需要心控的学员都是以宠物的形式出现的，不显示宠物就很尴尬了。。

**Comment by enderneko** [comment]
团队宠物可能依旧不会去做。
但会以另一种形式显示需要特别关注的目标（正在做）。
至于载具那个，单位按钮会自动从玩家变为他的载具。当前版本（r117）本无法点击选中该载具，但在即将发布的新版本中似乎解决了这个bug。

**Comment by eprendre** [comment]
感谢明确的答复，我会持续关注，万一哪天改变了主意呢。🤭
