### ISSUE TITLE
Feature request: Settings to show/hide individual status indicators

### ISSUE THREAD

**Issue by haothitran** [enderneko/Cell#38]
It would be nice to have individual settings to enable/disable each status text indicator. Or be able to change the alpha to hide the text.

For example:
- Enable/disable "drinking" status text.
- Enable "afk" status text, but disable afk timer.

**Comment by enderneko** [comment]
Added alpha to each status text.
It will be released soon.

**Comment by haothitran** [comment]
Much appreciated.
