### ISSUE TITLE
Feature request: Horizontal centering for custom buffs/debuffs indicators

### ISSUE THREAD

**Issue by haothitran** [enderneko/Cell#39]
Request to have custom indicators for icons for buffs/debuffs have hortizonal center growth/orientation.

If you have a custom buff/debuff icons indicator anchored to UnitButton's center, the first icon will be centered. Then when the second icon that appears, it would push the first icon over so that the entire indicator is still centered on UnitButton.

**Comment by enderneko** [comment]
In next version, the parent frame of ICONS indicator will be dynamically resized.
It will help to achieve this effect you want.

**Comment by haothitran** [comment]
Much appreciated.
