### ISSUE TITLE
Remove debuff type border color

### ISSUE THREAD

**Issue by andarial100** [enderneko/Cell#40]
Hi, is it possible to get an option to remove the debuff type border color so it looks like Blizzard base frames? I use the dispel type icons on the top right and I don't need the border colors to identify which type of debuff it is. Thank you.

**Comment by enderneko** [comment]
![rdtbc](https://user-images.githubusercontent.com/16433215/197169718-d1b2c265-4aa1-4fc9-a241-6e2a3f6cb501.gif)
Try this snippet: https://github.com/enderneko/Cell/blob/master/.snippets/RemoveDispelTypeBorderColor.lua
1> Cell Options -> About -> Code Snippets
2> Create new, paste, then save
3> Tick autorun checkbox
4> Reload

**Comment by andarial100** [comment]
Thanks, this is exactly what I wanted.
