### ISSUE TITLE
Cooldown swipe on icons

### ISSUE THREAD

**Issue by andarial100** [enderneko/Cell#42]
Hi, would it be possible to add cooldown swipe to icons as a third option to display remaining cd? Thanks in advance.

**Comment by enderneko** [comment]
Try https://github.com/enderneko/Cell/blob/master/.snippets/CooldownIcons_BlizzardStyle.lua
I'm not sure if it works.
Set COLOR_BORDER_BY_DISPEL_TYPE to false if you don't want colored borders.

**Comment by andarial100** [comment]
Thanks, it works perfectly. I do have a question about disabling the "Edge" on the cooldown swipe - is there a block of code I can remove to disable that? Alternatively is it possible to place in a true/false setting for enabling/disabling Edge the same way you did for border color?

**Comment by enderneko** [comment]
Updated.
Added a DRAW_EDGE variable.

**Comment by andarial100** [comment]
Thanks so much again!
