### ISSUE TITLE
护盾模拟错误

### ISSUE THREAD

**Issue by momo2366** [enderneko/Cell#43]
Hi 关于Wrath版本现在基于CLEU计算护盾的逻辑，有以下几个异常：
1. 盾雕文是可以暴击的，而盾不可以，所以需要计算当"SPELL_HEAL"事件中治疗为暴击时，模拟数据再/1.5
2. 泡泡盾现在是触发"SPELL_AURA_REMOVED"后直接清空，这会导致如果团队中有多个戒律牧师对同一个目标有泡泡盾时，有一个remove，所有数据都会清空，但护盾还是存在的
3. 泡泡盾是可以累加的，而且每个上限一万，所以仅等于上个暴击治疗的百分比是不准的
4. 可以基于泡泡盾的逻辑，再继续添加橙锤的模拟
以下是我在vuhdo的实现:
https://gitlab.vuhdo.io/vuhdo/vuhdo/-/merge_requests/62
https://gitlab.vuhdo.io/vuhdo/vuhdo/-/merge_requests/67
期望可以共同探讨团队框架特性的实现方式

**Comment by enderneko** [comment]
感谢分享！
确实，之前写的不仅没有考虑来源，也没有考虑盾的可叠加。
适配完DF版本之后，必将参考你的建议进行改正！

**Comment by enderneko** [comment]
- 刚才测试了下，确实，泡泡盾可以叠加
![da](https://user-images.githubusercontent.com/16433215/199103441-6918fc83-ed28-4369-993b-4db20e6df3b7.png)

- 上限的问题我也查了下，嗯，是目标等级*125，80级确实是10000
3.1.0的更新记录说明了这点（怀旧服应该没改吧？） https://wowpedia.fandom.com/wiki/Patch_3.1.0

- 不同牧师会在同一个目标上产生各自的泡泡盾buff（Cell不打算计算他人的泡泡盾）

- 橙锤的盾我也试着添加了（依然只管自己的） https://wowpedia.fandom.com/wiki/Val%27anyr,_Hammer_of_Ancient_Kings
由于我只能在正式服测试，Blessing 是在 HEAL 之后施加的，上限也不是蓝贴中的 20000，似乎和目标等级或总血量有一定关系，但我没怎么计算（或者说粗略计算了，但结果对不上），不清楚怀旧服是什么情况
另外，我没有保存触发Blessing效果时群体治疗法术的目标，只保存了最后受到该次治疗的目标。这样确实会导致群体治疗法术触发Blessing后的第一发盾有问题，之后再说吧（其实是打算用 timestamp 来区分是不是同一次治疗来的）

总之，感谢你的建议！
