### ISSUE TITLE
指示器—图标组不显示增益图标

### ISSUE THREAD

**Issue by pmzhudx** [enderneko/Cell#44]
你好，自从更新128版本之后，指示器-图标组-增益就不能正常工作了。图标组中的所有BUFF都不会显示，必须进入设置修改方向才能显示。
![image](https://user-images.githubusercontent.com/48729299/198320549-ca1e02c4-c0f7-4286-876d-b21237bed2a8.png)
如果之前方向为上下，必学修改为左右才能出现BUFF图标。反之如果之前方向为左右，必须修改为上下才能出现BUFF图标。但是一旦重载界面，又不显示BUFF图标了。
并且在修改方向能显示之后，我两个不同职业使用同一套指示器的配置，同一个图标组的位置似乎有很小的不同，我也搞不懂了。

我看到在128中更新了图标组的方向可以上下排列之后才出现这个问题。我自己恢复默认配置还是解决不了，只能请您看看了。

**Comment by enderneko** [comment]
尝试创建了几个图标组指示器，无法复现这个问题，无论是何种方向均能正常显示。

**Comment by enderneko** [comment]
使用r132版本，如果可以尝试彻底重置Cell再尝试。
如有报错，附上错误信息。

**Comment by pmzhudx** [comment]
在您确认了插件没问题之后我又测试了下，终于发现是鬼灵面具的代码片段导致的问题，去掉代码片段图标组就工作正常了。
感谢您的回复。我始终没想到可能是代码片段导致的问题，就一直没去动它。直到删除配置再次启用鬼灵面具之后图标组又不显示才发现。
我不用法夜了，哭死。

另外提个我的需求，减伤哪里图标能选择宽高，图标可以变成矩形而不是正方形，感觉能节约些显示面积。能不能对图标组也开放调整图标的宽高选项呢？

![image](https://user-images.githubusercontent.com/48729299/198558984-42d94c0a-58a0-437f-a769-9ae348177b30.png)

最近为了适配WLK和DF，几乎每天都能看见您更新新功能，让治疗变成轻松方便了许多。这是我用过的最好的框架了，真的实现了您的设置不复杂，但足够强大的设计目标，非常感谢您。

**Comment by enderneko** [comment]
确实，代码片段会导致这种问题，如果有大改，我应该先强行禁用代码片段并提示用户手动启用。
鬼灵面具代码片段我刚更新了下，应该没问题了。
https://github.com/enderneko/Cell/blob/master/.snippets/HauntedMaskIcons.lua
嗯，关于尺寸分开调节的建议可以，下个版本改。

**Comment by enderneko** [comment]
不用敬语啦！怪怪的🤣

**Comment by enderneko** [comment]
将 r134 中的代码片段的 CELL_RECTANGULAR_CUSTOM_INDICATOR_ICONS 设置为 true，就可以实现矩形图标了，仅限自定义图标（组）指示器。
