### ISSUE TITLE
能不能有选项总是置顶玩家自己

### ISSUE THREAD

**Issue by jbw2022** [enderneko/Cell#45]
在Vuhdo上有这样的选项，总是置顶玩家自己在小队中的框架。大神能不能安排一下~

**Comment by enderneko** [comment]
Cell 与 VuhDo 实现方式不同，Cell 在战斗中出现人员变化不会有任何问题，但 VuhDo 会。
同时这也与我“保持和团队标准排序一致”的理念相悖，因此 Cell 不会有这个功能。
