### ISSUE TITLE
希望在法术指示器自定义中加入黑名单

### ISSUE THREAD

**Issue by zhangsan249** [enderneko/Cell#48]
插件整体用下来整体很棒也很方便，但在使用过程中发现有些来自自身的触发性减伤技能我认为没有必要监视，但又无法调整隐藏它。希望能在指示器的自定义里面加入白名单与黑名单的分类。

**Comment by enderneko** [comment]
目前没有计划为这些内置指示器添加更多选项，目前已有添加额外法术的功能。
此建议短时间内都不会改动，优先级为低，还有其他的要改。
推荐自行创建指示器，然后禁用内置的，或者修改 Cell\Defaults\Indicators_DefaultSpells.lua。

**Comment by zhangsan249** [comment]
好的感谢提供修改文件的思路
