### ISSUE TITLE
有报错

### ISSUE THREAD

**Issue by sony6666** [enderneko/Cell#49]
Message: Interface/AddOns/Cell/Indicators/Base.lua:354: script ran too long
Time: Wed Nov  9 15:36:29 2022

Version: r137-release

**Comment by sony6666** [comment]
又有报错，主要出现在刚进到竞技场的时候就弹出来

Message: Interface/AddOns/Cell/Indicators/Built-in.lua:1158: script ran too long
Time: Wed Nov  9 22:34:04 2022
Count: 1
Stack: Interface/AddOns/Cell/Indicators/Built-in.lua:1158: script ran too long
[string "@Interface/AddOns/Cell/Indicators/Built-in.lua"]:1158: in function `SetPoint'
[string "@Interface/AddOns/Cell/Libs/PixelPerfect.lua"]:82: in function `Point'
[string "@Interface/AddOns/Cell/RaidFrame/UnitButton.lua"]:145: in function `func'
[string "@Interface/AddOns/Cell/Utils.lua"]:632: in function `IterateAllUnitButtons'
[string "@Interface/AddOns/Cell/RaidFrame/UnitButton.lua"]:136: in function `onEventFunc'
[string "@Interface/AddOns/Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Interface/AddOns/Cell/Core.lua"]:73: in function `UpdateLayout'
[string "@Interface/AddOns/Cell/Core.lua"]:103: in function `onEventFunc'
[string "@Interface/AddOns/Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Interface/AddOns/Cell/Core.lua"]:474: in function `?'
[string "@Interface/AddOns/Cell/Core.lua"]:699: in function <Interface/AddOns/Cell/Core.lua:698>

Locals: self = CellRaidFrameHeader7UnitButton4StatusText {
 0 = <userdata>
 SetStatus = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1136
 text = FontString {
 }
 SetFont = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1166
 points = <table> {
 }
 HideTimer = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1209
 ShowTimer = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1193
 colors = <table> {
 }
 SetPoint = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1152
 timer = FontString {
 }
 GetStatus = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1132
 OriginalSetPoint = <function> defined =[C]:-1
 SetColors = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1147
}
point = "BOTTOM"
_ = CellRaidFrameHeader7UnitButton4 {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 state = <table> {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 height = 63
 widget = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 indicators = <table> {
 }
 func = <table> {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 orientation = "horizontal"
 TopEdge = Texture {
 }
 0 = <userdata>
 Center = Texture {
 }
 width = 110
 backdropInfo = <table> {
 }
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 BottomEdge = Texture {
 }
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
yOffset = 0
(*temporary) = <function> defined =[C]:-1
(*temporary) = CellRaidFrameHeader7UnitButton4StatusText {
 0 = <userdata>
 SetStatus = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1136
 text = FontString {
 }
 SetFont = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1166
 points = <table> {
 }
 HideTimer = <function> defined @Interface/AddOns/Cell/Indicators/Built-in.lua:1209
 ShowTime

**Comment by enderneko** [comment]
尚不清楚造成问题的原因
需要稳定重现异常的方法

**Comment by sony6666** [comment]
竞技场又出问题，但团本不会，我加了几个DEUFF监测图标，是不是这个原因呢

Message: Interface/SharedXML/Backdrop.lua:429: script ran too long
Time: Fri Nov 11 19:21:39 2022
Count: 1
Stack: Interface/SharedXML/Backdrop.lua:429: script ran too long
[string "@Interface/SharedXML/Backdrop.lua"]:429: in function `SetBackdropBorderColor'
[string "@Interface/SharedXML/Backdrop.lua"]:324: in function `ApplyBackdrop'
[string "@Interface/SharedXML/Backdrop.lua"]:341: in function `SetBackdrop'
[string "@Interface/AddOns/Cell/Widgets/Widgets.lua"]:1500: in function `UpdatePixelPerfect'
[string "@Interface/AddOns/Cell/RaidFrame/UnitButton.lua"]:271: in function `func'
[string "@Interface/AddOns/Cell/Utils.lua"]:632: in function `IterateAllUnitButtons'
[string "@Interface/AddOns/Cell/RaidFrame/UnitButton.lua"]:136: in function `onEventFunc'
[string "@Interface/AddOns/Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Interface/AddOns/Cell/Core.lua"]:73: in function `UpdateLayout'
[string "@Interface/AddOns/Cell/Core.lua"]:103: in function `onEventFunc'
[string "@Interface/AddOns/Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Interface/AddOns/Cell/Core.lua"]:474: in function `?'
[string "@Interface/AddOns/Cell/Core.lua"]:699: in function <Interface/AddOns/Cell/Core.lua:698>

Locals: self = Frame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 points = <table> {
 }
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
r = 1
g = 1
b = 1
a = 1
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 BottomLeftCorner = <table> {
 }
 TopEdge = <table> {
 }
 BottomEdge = <table> {
 }
 Center = <table> {
 }
 RightEdge = <table> {
 }
 TopRightCorner = <table> {
 }
 TopLeftCorner = <table> {
 }
 LeftEdge = <table> {
 }
 BottomRightCorner = <table> {
 }
}
(for control) = "BottomEdge"
pieceName = "BottomEdge"
region = Texture {
 0 = <userdata>
}
(*temporary) = "BottomEdge"
(*temporary) = <table> {
 URx = 0.382813
 ULy = "repeatX"
 setHeight = true
 ULx = 0.382813
 URy = 0.062500
 LRy = 0.062500
 LRx = 0.492188
 LLy = "repeatX"
 LLx = 0.492188
}
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = "script ran too long"
textureUVs = <table> {
 BottomLeftCorner = <table> {
 }
 TopEdge = <table> {
 }
 BottomEdge = <table> {
 }
 Center = <table> {
 }
 RightEdge = <table> {
 }
 TopRightCorner = <table> {
 }
 TopLeftCorner = <table> {
 }
 LeftEdge = <table> {
 }
 BottomRightCorner = <table> {
 }
}
