### ISSUE TITLE
增益和debuff倒计时能否添加新的倒计时动画

### ISSUE THREAD

**Issue by yutian1224** [enderneko/Cell#5]
compactRaid的增减益都是类似时钟的转圈动画.
和目标框体一致,比较原生.可以添加进不,谢谢~

**Comment by enderneko** [comment]
嗯哼，下个版本或者下下个版本，很快就会有哒。

**Comment by 123fashaoyou** [comment]
可以给增减益价格介绍么，就是鼠标放在buff或debuff上会显示它的介绍
