### ISSUE TITLE
138版本报错

### ISSUE THREAD

**Issue by nicaihcy** [enderneko/Cell#50]
副本减益勾选鼠标提示后会有一个报错

Usage: GameTooltip:SetUnitAura("unit", [index][, "filter"])
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetUnitAura'
[string "@Interface/AddOns/Cell/Widgets/Tooltip.lua"]:63: in function `ShowTooltips'
[string "@Interface/AddOns/Cell/Indicators/Built-in.lua"]:870: in function <Interface/AddOns/Cell/Indicators/Built-in.lua:869>

Locals:
Skipped (In Encounter)

**Comment by enderneko** [comment]
已修，但距下版本发布还有些时间。
