### ISSUE TITLE
hi i have a new report 

### ISSUE THREAD

**Issue by liama11s** [enderneko/Cell#53]
5x Interface/AddOns/Cell/RaidFrame/UnitButton.lua:2318: attempt to call method 'ShowTooltips' (a nil value)
[string "@Interface/AddOns/Cell/RaidFrame/UnitButton.lua"]:2318: in function <Interface/AddOns/Cell/RaidFrame/UnitButton.lua:2312>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:266: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:322: in function <Interface/FrameXML/SecureHandlers.lua:306>
[string "=(tail call)"]: ?

Locals:
self = CellSoloFramePlayer {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 __updateElapsed = 0.228000
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 state = <table> {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 height = 56
 widget = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 indicators = <table> {
 }
 func = <table> {
 }
 fade = <table> {
 }
 0 = <userdata>
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 __unitName = "黑虍阿福"
 __unitGuid = "Player-963-06D404E1"
 BottomRightCorner = Texture {
 }
 __tickCount = 1
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 orientation = "horizontal"
 TopEdge = Texture {
 }
 __displayedGuid = "Player-963-06D404E1"
 Center = Texture {
 }
 width = 104
 backdropInfo = <table> {
 }
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 BottomEdge = Texture {
 }
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
}
unit = "player"
(*temporary) = nil
(*temporary) = <table> {
 UnitInGroup = <function> defined @Interface/AddOns/Cell/Utils.lua:993
 RemoveElementsByKeys = <function> defined @Interface/AddOns/Cell/Utils.lua:472
 GetTexCoord = <function> defined @Interface/AddOns/Cell/Utils.lua:1160
 UpdateTextWidth = <function> defined @Interface/AddOns/Cell/Utils.lua:740
 ShowGlowOptions = <function> defined @Interface/AddOns/Cell/Modules/GlowOptions.lua:286
 GetInstanceName = <function> defined @Interface/AddOns/Cell/Utils.lua:1299
 Sort = <function> defined @Interface/AddOns/Cell/Utils.lua:485
 ConvertHSBToRGB = <function> defined @Interface/AddOns/Cell/Utils.lua:230
 GetGroupType = <function> defined @Interface/AddOns/Cell/Utils.lua:983
 ShowIndicatorsExportFrame = <function> defined @Interface/AddOns/Cell/Modules/Indicators_Export.lua:273
 ShowTextureSelector = <function> defined @Interface/AddOns/Cell/Modules/Indicators_TextureSelector.lua:204
 RemoveElementsExceptKeys = <function> defined @Interface/AddOns/Cell/Utils.lua:459
 GetInstanceAndBossName = <function> defined @Interface/AddOns/Cell/Modules/RaidDebuffs.lua:2075
 GetDefaultSnippet = <function> defined @Interface/AddOns/Cell/Modules/CodeSnippets.lua:405
 UnitButton_OnLoad = <function> defined @Interface/AddOns/Cell/RaidFrame/UnitButton.lua:2435
 ShowLayoutExportFrame = <function> defined @Interface/AddOns/Cell/Modules/Layouts_ImportExport.lua:194
 GetInstanceAndBossId = <function> defined @Interface/AddOns/Cell/Modules/RaidDebuffs.lua:2049
 ConvertRGBToHEX = <function> defined @Interface/AddOns/Cell/Utils.lua:122
 CheckTableRemoved = <function> defined @Interface/AddOns/Cell/Utils.lua:553
 FitWidth = <function> defined @Interface/AddOns/Cell/Utils.lua:370
 ConvertRGB = <function> defined @Interface/AddOns/Cell/Utils.lua:110
 HideBlizzardRaid = <function> defined @Interface/AddOns/Cell/HideBlizzard.lua:70
 SecondsToTime = <function> defined @Interface/AddOns/Cell/Utils.lua:644
 GetClassColorStr = <function> defined @Interface/AddOns/Cell/Utils.lua:813
 ConvertTable = <function> defined @Interface/AddOns/Cell/Utils.lua:529
 ShowCodeSnippets = <function> defined @Interface/AddOns/Cell/Modules/CodeSnippets.lua:379
 GetTargetUnitID = <function> defined @Interface/AddOns/Cell/Utils.lua:1001
 ColorGradient

**Comment by jymaryb** [comment]
I have the same issue.

**Comment by enderneko** [comment]
There should be another lua error causing this issue.
I have no idea why this happens. 😫

**Comment by enderneko** [comment]
r141 is not compatible with 10.0.0
it's for 10.0.2
