### ISSUE TITLE
增益里面圣光闪烁技能无法显示

### ISSUE THREAD

**Issue by dzb8363622** [enderneko/Cell#55]
在增益指示器中设置了圣光闪烁技能之后，实际上依然无法在框架上正确的显示是否存在闪烁BUFF，准确的说是完全无法显示是否有闪烁存在

**Comment by enderneko** [comment]
![test](https://user-images.githubusercontent.com/16433215/205603215-8c2fd1b0-33ad-406a-aa5a-831d7a4bb0e6.png)
测试了图标/图标组/矩形/文本，没有问题。

**Comment by dzb8363622** [comment]
发现问题所在了，在天赋中圣光闪烁的id和你这张图的id完全不同，应该是技能id随着版本更新产生的问题，用你这个id添加指示器以后就可以正常工作了
