### ISSUE TITLE
Indicator - Aggro (border) not covering the full border on the bottom

### ISSUE THREAD

**Issue by timetofall** [enderneko/Cell#56]
Hello, 

Looks like the Aggro Border is not covering the bottom portion on the edge. Please see my attached screenshot, at the bottom its not going around the edge like on the top and sides. Any fix for this?

![image](https://user-images.githubusercontent.com/45275473/210191235-9d459921-e883-4eb7-b11b-d85d68ae00a2.png)

**Comment by enderneko** [comment]
This is a scaling issue.
I'll try to fix it later.

**Comment by timetofall** [comment]
Saw you did the update, just tested and it seems good now! Thank you
