### ISSUE TITLE
Continued development

### ISSUE THREAD

**Issue by xiomatic** [enderneko/Cell#57]
Hello,

I am saddened to hear about CN servers potentially closing down. I hope you can continue to play WOW if you like. I just want to ask if you plan on continuing to develop this Addon which I really like and if not, do you have anyone to take over? Thank you very much.

**Comment by enderneko** [comment]
Actually, I had not been playing WoW for almost two years. Until last month, I returned.
I kept Cell up to date during that time (tested on PTR).
**Cell will never be abandoned.**

But I have no plans to play WoW on other regions. So these raid debuffs may not be updated in time or be accurate.
