### ISSUE TITLE
Cell with elvui.

### ISSUE THREAD

**Issue by romonlol** [enderneko/Cell#58]
so i trying to use Cell with Elvui, all group frames in elvui disabled.
Party frames sometimes working just fine, but raid frames is a total mess.
![image](https://user-images.githubusercontent.com/19741736/210256604-95247798-81f5-45ec-bd9c-2575c9264c17.png)
`1x Cell/Indicators/Built-in.lua:1109: bad argument #1 to 'strlower' (string expected, got nil)
[string "=[C]"]: in function `strlower'
[string "@Cell/Indicators/Built-in.lua"]:1109: in function `SetFont'
[string "@Cell/RaidFrame/UnitButton.lua"]:195: in function `func'
[string "@Cell/Utils.lua"]:659: in function `IterateAllUnitButtons'
[string "@Cell/RaidFrame/UnitButton.lua"]:141: in function `onEventFunc'
[string "@Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Cell/Core.lua"]:72: in function `UpdateLayout'
[string "@Cell/Core.lua"]:106: in function `onEventFunc'
[string "@Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Cell/Core.lua"]:559: in function `GROUP_ROSTER_UPDATE'
[string "@Cell/Core.lua"]:657: in function `?'
[string "@Cell/Core.lua"]:725: in function <Cell/Core.lua:724>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"`
`1x Cell/Indicators/Built-in.lua:888: bad argument #1 to 'strlower' (string expected, got nil)
[string "=[C]"]: in function `strlower'
[string "@Cell/Indicators/Built-in.lua"]:888: in function `SetFont'
[string "@Cell/RaidFrame/UnitButton.lua"]:195: in function `func'
[string "@Cell/Utils.lua"]:659: in function `IterateAllUnitButtons'
[string "@Cell/RaidFrame/UnitButton.lua"]:141: in function `onEventFunc'
[string "@Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Cell/Core.lua"]:72: in function `UpdateLayout'
[string "@Cell/Core.lua"]:113: in function `onEventFunc'
[string "@Cell/Libs/CallbackHandler.lua"]:24: in function `Fire'
[string "@Cell/Core.lua"]:487: in function `?'
[string "@Cell/Core.lua"]:725: in function <Cell/Core.lua:724>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"`
`52x Cell/Indicators/Built-in.lua:1083: attempt to index field 'colors' (a nil value)
[string "@Cell/Indicators/Built-in.lua"]:1083: in function `SetStatus'
[string "@Cell/RaidFrame/UnitButton.lua"]:1777: in function <Cell/RaidFrame/UnitButton.lua:1757>
[string "@Cell/RaidFrame/UnitButton.lua"]:2137: in function <Cell/RaidFrame/UnitButton.lua:2084>

Locals:
self = CellPartyFrameHeaderUnitButton4StatusText {
 0 = <userdata>
 SetStatus = <function> defined @Cell/Indicators/Built-in.lua:1078
 text = FontString {
 }
 status = "AFK"
 HideTimer = <function> defined @Cell/Indicators/Built-in.lua:1151
 ShowTimer = <function> defined @Cell/Indicators/Built-in.lua:1135
 SetFont = <function> defined @Cell/Indicators/Built-in.lua:1108
 SetPoint = <function> defined @Cell/Indicators/Built-in.lua:1094
 timer = FontString {
 }
 GetStatus = <function> defined @Cell/Indicators/Built-in.lua:1074
 OriginalSetPoint = <function> defined =[C]:-1
 SetColors = <function> defined @Cell/Indicators/Built-in.lua:1089
}
status = "AFK"
(*temporary) = <function> defined =[C]:-1
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "attempt to index field 'colors' (a nil value)"
statusText = CellPartyFrameHeaderUnitButton4StatusText {
 0 = <userdata>
 SetStatus = <function> defined @Cell/Indicators/Built-in.lua:1078
 text = FontString {
 }
 status = "AFK"
 HideTimer = <function> defined @Cell/Indicators/Built-in.lua:1151
 ShowTimer = <function> defined @Cell/Indicators/Built-in.lua:1135
 SetFont = <function> defined @Cell/Indicators/Built-in.lua:1108
 SetPoint = <function> defined @Cell/Indicators/Built-in.lua:1094
 timer = FontString {
 }
 GetStatus = <function> defined @Cell/Indicators/Built-in.lua:1074
 OriginalSetPoint = <function> defined =[C]:-1
 SetColors = <function> defined @Cell/Indicators/Built-in.lua:1089
}
text = FontString {
 0 = <userdata>
}
L = <table> {
 raidRosterTips = "[Right-Click] promote/demote (assistant). [Alt+Right-Click] uninvite."
 TOP = "Top"
 Unit = "Unit"
 togglemenu_nocombat = "Menu (not in combat)"
 Debuff = "Debuff"
 showStack = "Show stack text"
 BOTTOM = "Bottom"
 PET = "Pet"
 Raid = "Raid"
 enableHighlight = "Highlight unit button"
 Clear = "Clear"
 INVERT = "Invert"
 right-to-left = "Right to Left"
 ABOUT = "Cell is a unique raid frame addon inspired by CompactRaid.
I love CompactRaid so much, but it seems to be abandoned. And I made Cell, hope you enjoy.
Some ideas are from other great raid frame addons, such as Aptechka, Grid2 and VuhDo.
Cell is not meant to be a lightweight or powerful raid frame addon. It's easy to use and good enough for you (hope so)."
 dispellableByMe = "Only show debuffs dispellable by me"
 Buff = "Buff"
 pullTimerTips = "
|rPull Timer
Left-Click: |cffffffffstart timer|r
Right-Click: |cffffffffcancel timer|r"
 Externals + Defensives, no need to enable all of them = "Externals + Defensives, no need to enable all of them"
 hideIfEmptyOrFull = "Hide while HP is empty/full"
 showTooltip = "Show aura tooltip"
 Target = "Target"
 Icon = "Icon"
 CENTER = "Center"
 bottom-to-top = "Bottom to Top"
 TOPLEFT = "Top Left"
 Icons = "Icons"
 togglemenu = "Menu"
 onlyShowTopGlow = "Only show glow for the first debuff"
 syncTips = "Set the master layout here
All indicators of slave layout are fully in-sync with the master
It's a two-way sync, but all indicators of slave layout will be lost when set a master"
 RAID_DEBUFFS_TIPS = "Tips: [Drag & Drop] to change debuff order. [Double-Click] on instance name to open Encounter Journal. [Shift+Left Click] on instance/boss name to share debuffs. [Alt+Left Click] on instance/boss name to reset debuffs. The priority of General Debuffs is higher than Boss Debuffs."
 showDuration = "Show duration text"
 readyCheckTips = "
|rReady Check
Left-Click: |cffffffffinitiate a ready check|r
Right-Click: |cffffffffstart a role check|r"
 Target of Target = "Target of Target"
 top-to-bottom = "Top to Bottom"
 This will make these icons not click-through-able = "This will make these icons not click-through-able"
 Focus = "Focus"
 assist = "Assist"
 BOTTOMLEFT = "Bottom Left"
 Texture = "Texture"
 Unit's Pet = "Unit's Pet"
 hideDama`
 Looks like Cell and elvui have some conflicts or its some another addons.
And Layouts option is just empty blank.

**Comment by enderneko** [comment]
Cell is compatible with ElvUI. I'm also using it.
This is a weird issue caused by the font setting of Status Text indicator.
I'll try to fix it.

**Comment by romonlol** [comment]
working like a charm with last update.
Aprreciate your hard work.
