### ISSUE TITLE
Click-Casting Issue + Suggestion

### ISSUE THREAD

**Issue by Xoogle5M** [enderneko/Cell#59]
Tranquility is not available as a Click-Casting spell under spells 

Also, when trying to set "T" as a button to use, it sets it to "Talent" instead of "T" (see on the left: https://imgur.com/EAR2MDa)

An option to have custom sorting would be nice too :) Some people prefer to have tank at top, dps in middle and healer at bottom for example.

**Comment by enderneko** [comment]
Fixed wrong display of key bindings.
Spells like Tranquility are not included in Cell. But you can add it manually by selecting spell->edit and filling in the spell name.

I'm afraid there's no plan to add more sorting methods at the moment.
