### ISSUE TITLE
指示器法术列表问题

### ISSUE THREAD

**Issue by yutian1224** [enderneko/Cell#6]
在指示器sheet中添加新的指示器,填写的是法术列表,但是图标只会显示最近获得的那个.
是不是应该做个向左或者向右的自增列表框~

顺便问一下指示器中的:减益(中间),木有看到相关配置,是会提示哪些减益呢~

**Comment by enderneko** [comment]
嗯，是的，如果在一个指示器内填入同一个职业天赋的多个法术，那么只会匹配并显示“该单位索引最大的增益”。设计上就是不打算让其展开的，不过之后会改成法术列表的优先级自上而下递增。
至于动态展开的那种应该会做成另外一个指示器的。
以上改动目测在一周内更新。

关于“减益(中间)”，其设置位于“副本减益”页面中，目前9.0的列表还是空白，不过在开团本前会更新的，8.0的列表是有内容的，可以参考下。

**Comment by enderneko** [comment]
顺带一提，指示器中的法术列表的本意是让使用者添加”不需要同时显示的增减益“。
它的配置是从属于”布局“的，并且是账号配置，而不是角色。
所以我的推荐是，在一个指示器内添加不同职业或天赋的法术。
