### ISSUE TITLE
Constant LUA errors in 25m Flame Leviathan fight - Wrath

### ISSUE THREAD

**Issue by volostyle** [enderneko/Cell#65]
During this fight I get constant LUA errors, but only on 25m. I don't seem to have any issue on 10m:

`395x Cell/Indicators/Custom_Wrath.lua:163: attempt to index field '?' (a nil value)
[string "@Cell/Indicators/Custom_Wrath.lua"]:163: in function `ResetCustomIndicators'
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:632: in function <Cell/RaidFrame/UnitButton_Wrath.lua:615>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:1418: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1412>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:1942: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1921>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:2030: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1964>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:2186: in function <Cell/RaidFrame/UnitButton_Wrath.lua:2184>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/SecureGroupHeaders.lua"]:223: in function <FrameXML/SecureGroupHeaders.lua:130>
[string "@FrameXML/SecureGroupHeaders.lua"]:630: in function `SecureGroupPetHeader_Update'
[string "@FrameXML/SecureGroupHeaders.lua"]:514: in function <FrameXML/SecureGroupHeaders.lua:512>

Locals:
self = <table> {
 CreateAura_Icons = <function> defined @Cell/Indicators/Base.lua:860
 UpdateCustomIndicators = <function> defined @Cell/Indicators/Custom_Wrath.lua:192
 UpdateConsumablesOrientation = <function> defined @Cell/Indicators/Consumables.lua:489
 RemoveAllCustomIndicators = <function> defined @Cell/Indicators/Custom_Wrath.lua:90
 CreateAura_Bar = <function> defined @Cell/Indicators/Base.lua:737
 RemoveIndicator = <function> defined @Cell/Indicators/Custom_Wrath.lua:79
 CreateIndicator = <function> defined @Cell/Indicators/Custom_Wrath.lua:25
 EnableConsumables = <function> defined @Cell/Indicators/Consumables.lua:505
 GetDefaultConsumables = <function> defined @Cell/Defaults/Indicators_DefaultSpells_Wrath.lua:332
 ConvertConsumables = <function> defined @Cell/Defaults/Indicators_DefaultSpells_Wrath.lua:336
 CreateAura_BarIcon = <function> defined @Cell/Indicators/Base.lua:318
 IsDrinking = <function> defined @Cell/Defaults/Indicators_DefaultSpells_Wrath.lua:235
 ResetCustomIndicators = <function> defined @Cell/Indicators/Custom_Wrath.lua:143
 CreateAllCooldowns = <function> defined @Cell/Indicators/Built-in.lua:158
 CreateTargetedSpells = <function> defined @Cell/Indicators/TargetedSpells.lua:159
 CreateRoleIcon = <function> defined @Cell/Indicators/Built-in.lua:1229
 UpdateStatusIcon_Resurrection = <function> defined @Cell/Indicators/StatusIcon.lua:149
 CreateConsumables = <function> defined @Cell/Indicators/Consumables.lua:441
 GetDebuffGlow = <function> defined @Cell/Indicators/Built-in.lua:622
 CreateLeaderIcon = <function> defined @Cell/Indicators/Built-in.lua:1283
 CreateAura_Texture = <function> defined @Cell/Indicators/Base.lua:833
 CreateAura_BorderIcon = <function> defined @Cell/Indicators/Base.lua:110
 EnableStatusIcon = <function> defined @Cell/Indicators/StatusIcon.lua:311
 CreateHealthText = <function> defined @Cell/Indicators/Built-in.lua:1157
 EnableTargetedSpells = <function> defined @Cell/Indicators/TargetedSpells.lua:264
 CreatePlayerRaidIcon = <function> defined @Cell/Indicators/Built-in.lua:827
 CreateTargetRaidIcon = <function> defined @Cell/Indicators/Built-in.lua:842
 UpdateStatusIcon = <function> defined @Cell/Indicators/StatusIcon.lua:267
 CreateTargetCounter = <function> defined @Cell/Indicators/TargetCounter.lua:128
 EnableAoEHealing = <function> defined @Cell/Indicators/AoEHealing.lua:89
 CreateAura_Rect = <function> defined @Cell/Indicators/Base.lua:645
 EnableTargetCounter = <function> defined @Cell/Indicators/TargetCounter.lua:113
 CanDispel = <function> defined @Cell/Defaults/Indicators_DefaultSpells_Wrath.lua:207
 CreateAura_Text = <function> defined @Cell/Indicators/Base.lua:554
 UpdateHealthThresholds = <function> defined @Cell/Indicators/Built-in.lua:1548
 GetSummonDuration = <function> defined @Cell/Defaults/Indicators_DefaultSpells_Wrath.lua:77
 CreateStatusIcon = <function> defined @Cell/Indicators/StatusIcon.lua:61
 CreateDefensiveCooldowns = <function> defined @Cell/Indicators/Built-in.lua:105
 CreateExternalCooldowns = <function> defined @Cell/Indicators/Built-in.lua:135
 CreateHealthThresholds = <function> defined @Cell/Indicators/Built-in.lua:1469
 CreateShieldBar = <function> defined @Cell/Indicators/Built-in.lua:1431
 CreateAggroBlink = <function> defined @Cell/Indicators/Built-in.lua:1386
 IsDefensiveCooldown = <function> defined @Cell/Defaults/`

**Comment by diw1** [comment]
151x Cell/Indicators/Custom_Wrath.lua:163: attempt to index field '?' (a nil value)
[string "@Cell/Indicators/Custom_Wrath.lua"]:163: in function `ResetCustomIndicators'
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:872: in function <Cell/RaidFrame/UnitButton_Wrath.lua:864>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:1459: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1452>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:1982: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1961>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:2070: in function <Cell/RaidFrame/UnitButton_Wrath.lua:2004>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:2226: in function <Cell/RaidFrame/UnitButton_Wrath.lua:2224>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/SecureGroupHeaders.lua"]:223: in function <FrameXML/SecureGroupHeaders.lua:130>
[string "@FrameXML/SecureGroupHeaders.lua"]:630: in function `SecureGroupPetHeader_Update'
[string "@FrameXML/SecureGroupHeaders.lua"]:514: in function <FrameXML/SecureGroupHeaders.lua:512>

Locals:
self = <table> {
 ShowMissingBuff = <function> defined @Cell/Indicators/Built-in.lua:1645
 GetDefaultConsumables = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:385
 ConvertConsumables = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:389
 CreateAura_BarIcon = <function> defined @Cell/Indicators/Base.lua:316
 IsDrinking = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:288
 ResetCustomIndicators = <function> defined @Cell/Indicators/Custom_Wrath.lua:143
 CreateRoleIcon = <function> defined @Cell/Indicators/Built-in.lua:1233
 UpdateStatusIcon_Resurrection = <function> defined @Cell/Indicators/StatusIcon.lua:149
 CreateAggroBorder = <function> defined @Cell/Indicators/Built-in.lua:1338
 CreateAura_BorderIcon = <function> defined @Cell/Indicators/Base.lua:108
 CreateHealthText = <function> defined @Cell/Indicators/Built-in.lua:1161
 CreatePlayerRaidIcon = <function> defined @Cell/Indicators/Built-in.lua:828
 UpdateHealthThresholds = <function> defined @Cell/Indicators/Built-in.lua:1560
 EnableTargetedSpells = <function> defined @Cell/Indicators/TargetedSpells.lua:264
 CreateStatusText = <function> defined @Cell/Indicators/Built-in.lua:1057
 CreateDefensiveCooldowns = <function> defined @Cell/Indicators/Built-in.lua:105
 IsExternalCooldown = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:144
 CreateAura_Color = <function> defined @Cell/Indicators/Base.lua:763
 GetDefaultTargetedSpellsList = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:369
 CreateAggroBlink = <function> defined @Cell/Indicators/Built-in.lua:1398
 CreateDebuffs = <function> defined @Cell/Indicators/Built-in.lua:326
 CreateNameText = <function> defined @Cell/Indicators/Built-in.lua:861
 CreateAoEHealing = <function> defined @Cell/Indicators/AoEHealing.lua:42
 GetDefaultDebuffBlacklist = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:15
 GetDebuffOrder = <function> defined @Cell/Indicators/Built-in.lua:608
 CanDispel = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:260
 EnableMissingBuffs = <function> defined @Cell/Indicators/Built-in.lua:1594
 SetDebuffTypeColor = <function> defined @Cell/Defaults/Indicator_Defaults.lua:16
 CreateAllCooldowns = <function> defined @Cell/Indicators/Built-in.lua:158
 CreateTargetedSpells = <function> defined @Cell/Indicators/TargetedSpells.lua:159
 GetDebuffTypeColor = <function> defined @Cell/Defaults/Indicator_Defaults.lua:8
 GetDebuffGlow = <function> defined @Cell/Indicators/Built-in.lua:623
 CreateLeaderIcon = <function> defined @Cell/Indicators/Built-in.lua:1295
 CreateAura_Texture = <function> defined @Cell/Indicators/Base.lua:831
 UpdateConsumablesOrientation = <function> defined @Cell/Indicators/Consumables.lua:489
 EnableStatusIcon = <function> defined @Cell/Indicators/StatusIcon.lua:311
 UpdateExternals = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:116
 CreateTargetRaidIcon = <function> defined @Cell/Indicators/Built-in.lua:843
 UpdateStatusIcon = <function> defined @Cell/Indicators/StatusIcon.lua:267
 GetDefensives = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:200
 CreateAura_Rect = <function> defined @Cell/Indicators/Base.lua:643
 EnableTargetCounter = <function> defined @Cell/Indicators/TargetCounter.lua:113
 UpdateCustomIn


Same here. Bump Bump

**Comment by volostyle** [comment]
This error only seems to happen when pet frames are enabled in 25m. If I disable the pet frames, the error goes away. If I do 10m with pet frames, I don't have any errors.

**Comment by enderneko** [comment]
Does this issue still exist in r163?

**Comment by volostyle** [comment]
Yes, still getting this LUA constantly:

18x Cell/Indicators/Custom_Wrath.lua:159: attempt to index field '?' (a nil value)
[string "@Cell/Indicators/Custom_Wrath.lua"]:159: in function `ResetCustomIndicators'
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:629: in function <Cell/RaidFrame/UnitButton_Wrath.lua:611>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:1452: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1446>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:1976: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1955>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:2064: in function <Cell/RaidFrame/UnitButton_Wrath.lua:1998>
[string "@Cell/RaidFrame/UnitButton_Wrath.lua"]:2220: in function <Cell/RaidFrame/UnitButton_Wrath.lua:2218>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/SecureGroupHeaders.lua"]:223: in function <FrameXML/SecureGroupHeaders.lua:130>
[string "@FrameXML/SecureGroupHeaders.lua"]:630: in function `SecureGroupPetHeader_Update'
[string "@FrameXML/SecureGroupHeaders.lua"]:514: in function <FrameXML/SecureGroupHeaders.lua:512>

Locals:
self = <table> {
 ShowMissingBuff = <function> defined @Cell/Indicators/Built-in.lua:1645
 GetDefaultConsumables = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:385
 ConvertConsumables = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:389
 CreateAura_BarIcon = <function> defined @Cell/Indicators/Base.lua:316
 IsDrinking = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:288
 ResetCustomIndicators = <function> defined @Cell/Indicators/Custom_Wrath.lua:136
 CreateRoleIcon = <function> defined @Cell/Indicators/Built-in.lua:1233
 UpdateStatusIcon_Resurrection = <function> defined @Cell/Indicators/StatusIcon.lua:149
 CreateAggroBorder = <function> defined @Cell/Indicators/Built-in.lua:1338
 CreateAura_BorderIcon = <function> defined @Cell/Indicators/Base.lua:108
 CreateHealthText = <function> defined @Cell/Indicators/Built-in.lua:1161
 CreatePlayerRaidIcon = <function> defined @Cell/Indicators/Built-in.lua:828
 UpdateHealthThresholds = <function> defined @Cell/Indicators/Built-in.lua:1560
 EnableTargetedSpells = <function> defined @Cell/Indicators/TargetedSpells.lua:264
 CreateStatusText = <function> defined @Cell/Indicators/Built-in.lua:1057
 CreateDefensiveCooldowns = <function> defined @Cell/Indicators/Built-in.lua:105
 IsExternalCooldown = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:144
 CreateAura_Color = <function> defined @Cell/Indicators/Base.lua:763
 GetDefaultTargetedSpellsList = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:369
 CreateAggroBlink = <function> defined @Cell/Indicators/Built-in.lua:1398
 CreateDebuffs = <function> defined @Cell/Indicators/Built-in.lua:326
 CreateNameText = <function> defined @Cell/Indicators/Built-in.lua:861
 CreateAoEHealing = <function> defined @Cell/Indicators/AoEHealing.lua:42
 GetDefaultDebuffBlacklist = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:15
 GetDebuffOrder = <function> defined @Cell/Indicators/Built-in.lua:608
 CanDispel = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:260
 EnableMissingBuffs = <function> defined @Cell/Indicators/Built-in.lua:1594
 SetDebuffTypeColor = <function> defined @Cell/Defaults/Indicator_Defaults.lua:16
 CreateAllCooldowns = <function> defined @Cell/Indicators/Built-in.lua:158
 CreateTargetedSpells = <function> defined @Cell/Indicators/TargetedSpells.lua:159
 GetDebuffTypeColor = <function> defined @Cell/Defaults/Indicator_Defaults.lua:8
 GetDebuffGlow = <function> defined @Cell/Indicators/Built-in.lua:623
 CreateLeaderIcon = <function> defined @Cell/Indicators/Built-in.lua:1295
 CreateAura_Texture = <function> defined @Cell/Indicators/Base.lua:831
 UpdateConsumablesOrientation = <function> defined @Cell/Indicators/Consumables.lua:489
 EnableStatusIcon = <function> defined @Cell/Indicators/StatusIcon.lua:311
 UpdateExternals = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:116
 CreateTargetRaidIcon = <function> defined @Cell/Indicators/Built-in.lua:843
 UpdateStatusIcon = <function> defined @Cell/Indicators/StatusIcon.lua:267
 GetDefensives = <function> defined @Cell/Defaults/Indicator_DefaultSpells_Wrath.lua:200
 CreateAura_Rect = <function> defined @Cell/Indicators/Base.lua:643
 EnableTargetCounter = <function> defined @Cell/Indicators/TargetCounter.lua:113
 UpdateCustomIn

**Comment by volostyle** [comment]
This seems to be resolved with the latest release. I was able to do a 25m last night without any errors.
