### ISSUE TITLE
BUG: 团队标签框架移动队友异常

### ISSUE THREAD

**Issue by yutian1224** [enderneko/Cell#7]
团队标签显示的框架中移动队员的时候.
大概率会导致鼠标和当前移动的队友框绑定,无法做出其他操作.
只能重启游戏解决~

**Comment by enderneko** [comment]
有没有报错？ 我在我几个号上都没出现这个问题。

**Comment by yutian1224** [comment]
报错打开试了下,貌似没相关信息,也不是每次必现
把队友拽拖过程中就可能会出现,截图这个框体外的队友是鼠标位置,已经和队友条绑定,没法释放,点击和做其他操作了
![图片](https://user-images.githubusercontent.com/13673671/99134875-ad386b00-265a-11eb-92e4-c50576f8a13d.png)

**Comment by yutian1224** [comment]
刚抓到一个报错

`Message: Interface\AddOns\Cell\RaidFrame\UnitButton.lua:1589: attempt to perform arithmetic on field '?' (a nil value)
Time: Sat Nov 14 09:52:18 2020
Count: 17
Stack: Interface\AddOns\Cell\RaidFrame\UnitButton.lua:1589: attempt to perform arithmetic on field '?' (a nil value)
[string "@Interface\AddOns\Cell\RaidFrame\UnitButton.lua"]:1589: in function `TimerTextOnUpdate'
[string "@Interface\AddOns\Cell\RaidFrame\UnitButton.lua"]:1294: in function <Interface\AddOns\Cell\RaidFrame\UnitButton.lua:1281>
[string "@Interface\AddOns\Cell\RaidFrame\UnitButton.lua"]:1305: in function <Interface\AddOns\Cell\RaidFrame\UnitButton.lua:1302>

Locals: (*temporary) = 40919.564000
(*temporary) = nil
(*temporary) = "Player-1933-07702BB6"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field '?' (a nil value)"
button = CellGroupHeaderSubGroup4UnitButton1 {
 __tickCount = 2
 indicators = <table> {
 }
 __displayedGuid = "Player-1933-07702BB6"
 func = <table> {
 }
 state = <table> {
 }
 __updateElapsed = 0.233000
 0 = <userdata>
 widget = <table> {
 }
 updateRequired = 1
}
GetTime = <function> defined =[C]:-1
startTimeCache = <table> {
 Player-1668-027108A3 = 40871.372000
 Player-707-062DB7F5 = 40898.177000
 Player-1498-01DC8802 = 40908.611000
 Player-877-05AC478E = 40786.222000
 Player-1498-01D7DB6F = 40901.244000
 Player-962-04FC7490 = 40815.306000
 Player-816-032DFEB6 = 40780.956000
 Player-826-0542F45C = 40544.563000
 Player-714-062719C2 = 40544.883000
 Player-1943-03B42DEA = 40814.006000
 Player-817-04A36729 = 40815.072000
 Player-826-03ECE98B = 40907.344000
 Player-714-0597D41A = 40890.644000
 Player-741-05C1359F = 40544.563000
}
timerText = CellGroupHeaderSubGroup4UnitButton1TimerText {
 0 = <userdata>
}
F = <table> {
 UnitInGroup = <function> defined @Interface\AddOns\Cell\Utils.lua:312
 RemoveElementsByKeys = <function> defined @Interface\AddOns\Cell\Utils.lua:72
 GetTexCoord = <function> defined @Interface\AddOns\Cell\Utils.lua:410
 UpdateTextWidth = <function> defined @Interface\AddOns\Cell\Utils.lua:203
 GetInstanceName = <function> defined @Interface\AddOns\Cell\Utils.lua:442
 ShowRaidRosterFrame = <function> defined @Interface\AddOns\Cell\ToolFrames\RaidRosterFrame.lua:266
 CreateCentralDebuff = <function> defined @Interface\AddOns\Cell\RaidFrame\Elements\Auras.lua:887
 IsDrinking = <function> defined @Interface\AddOns\Cell\OptionFrames\Indicators_DefaultSpells.lua:320
 GetFontItems = <function> defined @Interface\AddOns\Cell\Utils.lua:371
 UpdateFont = <function> defined @Interface\AddOns\Cell\Core.lua:74
 CheckCustomIndicators = <function> defined @Interface\AddOns\Cell\RaidFrame\Elements\Auras.lua:1018
 UnitButton_OnLoad = <function> defined @Interface\AddOns\Cell\RaidFrame\UnitButton.lua:1349
 SavePosition = <function> defined @Interface\AddOns\Cell\Utils.lua:429
 CheckTableRemoved = <function> defined @Interface\AddOns\Cell\Utils.lua:133
 GetFont = <function> defined @Interface\AddOns\Cell\Utils.lua:361
 RestorePosition = <function> defined @Interface\AddOns\Cell\Utils.lua:434
 TInsert = <function> defined @Interface\AddOns\Cell\Utils.lua:61
 CreateExternalCooldowns = <function> defined @Interface\AddOns\Cell\RaidFrame\Elements\Auras.lua:682
 Copy = <function> defined @Interface\AddOns\Cell\Utils.lua:42
 UpdateFrameLock = <function> defined @Interface\AddOns\Cell\RaidFrame\MainFrame.lua:60
 HideBlizzard = <function> defined @Interface\AddOns\Cell\HideBlizzard.lua:47
 TableToString = <function> defined @Interface\AddOns\Cell\Utils.lua:121
 UpperFirst = <function> defined @Interface\AddOns\Cell\Utils.lua:8
 GetSpellInfo = <function> defined @Interface\AddOns\Cell\Utils.lua:477
 GetDebuffList = <function> defined @Interface\AddOns\Cell\OptionFrames\RaidDebuffs.lua:1068
 CreateAoEHealing = <function> defined @Interface\AddOns\Cell\RaidFrame\Elements\Auras.lua:585
 ShowOptionsFrame = <function> defined @Interface\AddOns\Cell\OptionFrames\OptionsFrame.lua:80
 GetPetUnit = <funct`

**Comment by enderneko** [comment]
已尝试修复这个错误，不过这个错误是“离线”“暂离”计时器相关的。和那个换队界面完全没有关系…

不过，我还是没能重现换队界面拖动时的“粘住鼠标”的问题，也许可以考虑把你的插件打个包发给我，我再试试，可能有什么插件冲突也说不定。

**Comment by yutian1224** [comment]
很神奇,我也不知道触发原因,因为不是每次必现...我在队友进战斗的情况,自己进战斗的情况都试了
刚才等稀有的时候应该大家都没进战斗,测试了几分钟出现了一次.
![图片](https://user-images.githubusercontent.com/13673671/99139362-d7962280-2672-11eb-9b5e-d7e90a832ce9.png)

下面是插件包
[AddOns.zip](https://github.com/enderneko/Cell/files/5540186/AddOns.zip)

**Comment by enderneko** [comment]
我昨天试了下你的插件包，很迷，我的意思是里边那些Blizzard插件都是好早以前的了，虽然留着也没影响（没作用）。
其次就是EN_UnitFrames、GridClickSets、RelicInspector、SafeQueue、WoWDBProfiler，这几个插件，直接报错，他们要么上古版本，要么就是没更新。
在禁用了这几个后，我试了拖动，还是没重现问题……我太难了……

不过话说回来，你该好好收拾下你的插件文件夹了，插件删了重新下吧。

**Comment by yutian1224** [comment]
前一次整理应该是8.0刚开那会儿,都是上古时代的宝贝了 xD
我清理一下再测测哈,多谢啦~
