### ISSUE TITLE
feature request: 把libHealcomm直接加入到Libs下面

### ISSUE THREAD

**Issue by diw1** [enderneko/Cell#70]
现在怀旧服太依赖于Libhealcomm的治疗预估（游戏本身的非常破败，BLZ在3.4.1PTR之后就没有进行过任何维护），同类的插件（包括Grid2和Vuhdo）都有直接吧Libhealcomm放入自己的Libs中。 这样的话，会方便使用者自己，以及团队里其他治疗职业来收到healcomm的信息

**Comment by enderneko** [comment]
之前是内置的。
但，由于收到“LibHealComm会导致游戏卡顿”的反馈。
且，ElvUI自13.08版本也移除了内置的LibHealComm，这不是没有理由的。
故，Cell不会考虑将其内置。
