### ISSUE TITLE
Indestructible Potion missing from Consumables Indicator [Wrath]

### ISSUE THREAD

**Issue by volostyle** [enderneko/Cell#71]
I'm trying to add Indestructible Pots to the consumables indicator but it keeps saying invalid spell ID: 40093

Why does this not work?

**Comment by enderneko** [comment]
Spell ID is **NOT** Item ID.

I'm afraid you might have to find the ID by yourself, for I don't play classic wow.

1. Enable "Debug Mode" (just above the consumables list).
2. Use the potion.
3. The ID is shown in the chat frame.
