### ISSUE TITLE
Missing Main Tank/assist icons

### ISSUE THREAD

**Issue by telias82** [enderneko/Cell#74]
it has the role icons, but not the one similar to leader (small shield for tank, sword for assist)

can this be added?

**Comment by enderneko** [comment]
https://raw.githubusercontent.com/enderneko/Cell/master/.snippets/PartyAssignmentIcon.lua
Use this snippet.

![PartyAssignmentIcon](https://raw.githubusercontent.com/enderneko/Cell/master/.snippets/PartyAssignmentIcon.png)

If there are more requests about this, I'll add it as an indicator.

**Comment by telias82** [comment]
where do i put this snippet?

**Comment by enderneko** [comment]
1. Cell Options -> About -> Code Snippets
2. New -> Paste
3. Edit _point/relativePoint/x/y/size_ for your needs
4. Save -> Tick the AutoRun box
5. Reload

**Comment by enderneko** [comment]
The position of this assignment icon is relative to Leader Icon indicator.
