### ISSUE TITLE
[Wrath] - Power Bar Filters don't work correctly

### ISSUE THREAD

**Issue by volostyle** [enderneko/Cell#78]
I have the power bar filters configured to not show any power bars except for the healer roles. The only way I can get the power bars for healers to show is if I select the DPS sword icon, even though all healers have the healing role selected.

**Comment by enderneko** [comment]
![](https://raw.githubusercontent.com/enderneko/ImageUpload/master/filter.gif)
It works on my end.
Any lua errors?

**Comment by volostyle** [comment]
Ya I don't know, the only way I can get it to show up is to select the DPS role icon. Healer role won't show the power bar at all.

**Comment by volostyle** [comment]
Here it is in action. Power bar doesn't show while in healing role.

https://github.com/enderneko/Cell/assets/41602737/afd989c3-10bb-403d-b965-f9f302c2f85f

**Comment by volostyle** [comment]
Just sent it to your email.

**Comment by enderneko** [comment]
Thanks! I got it fixed.
Caused by Role Icon indicator. Nothing wrong with your config file.
I'll release it soon.
