### ISSUE TITLE
feature request: 在使用饰品旁边多增加一个使用手套的选项

### ISSUE THREAD

**Issue by diw1** [enderneko/Cell#79]
以及在怀旧服内，是否也可以增加missing buff的指示器

**Comment by enderneko** [comment]
嗯，加了“饰品、腕部、手”。

至于“缺失增益”指示器，怀旧服没做就是因为它的圣骑Buff太多，不知道如何下手。

**Comment by diw1** [comment]
那是否可以就在buff指示器里面，加一个checkbox，没有buff时显示。 做一个简单版的，这样方便他们在里面填入自己负责的buff即可

**Comment by enderneko** [comment]
我试试看能不能挤个缩水版的。
