### ISSUE TITLE
繁中翻譯已完成

### ISSUE THREAD

**Issue by class2u** [enderneko/Cell#8]
你好! 非常感謝你製作這麼好用的插件！一直以來都找不到簡單方便的團框，真是救了大家。
繁體中文的翻譯已經完成了，還要麻煩你放進插件裡面，再次感謝！
https://www.curseforge.com/wow/addons/cell/localization

**Comment by enderneko** [comment]
辛苦了！ 我稍微更新了下，多了几处需要翻译的地方呢，麻烦你啦。

**Comment by class2u** [comment]
已更新翻譯!! 你也辛苦啦!
