### ISSUE TITLE
关于恩护龙人的驱散高亮

### ISSUE THREAD

**Issue by shanluo911** [enderneko/Cell#80]
你好，之前玩奶龙的时候，我记得框子只会在中了魔法和中毒之后高亮。昨天发现所有的debuff都会让框体高亮。
驱散的设置没有改过，应该就是初始设定。
![image](https://github.com/enderneko/Cell/assets/74176112/84f1c015-055b-4d90-94ed-0bf94ccaa777)

我猜想这里的“只显示我能驱散的减益”是考虑了龙人的灼烧之焰技能，因为该技能能够驱散几乎所有的减益类型。但是我自己的体验来说，感觉不是特别好，主要原因有两点：
![image](https://github.com/enderneko/Cell/assets/74176112/74624d8d-a2c1-456c-b21b-46ff1ac07bb3)
- 这个技能cd很长，有一分钟。不管这个技能有没有进cd，框体都会高亮，给人一种可以驱散的错觉。（虽然常规的8s驱散，同样也会在进cd的时候高亮，但是毕竟cd短。）
- 其他的治疗只有常规驱散，如果同时玩奶龙的话，就会感觉很别扭。会以为这是8s的常规驱散就能够驱散的减益。

想问下有没有办法让奶龙只高亮魔法和中毒的办法，谢谢。

**Comment by enderneko** [comment]
嗯，这个法术是r169版本中加入的。
最初的时候我也是觉得这个法术CD太长，就没加入，上次收到了几个请求，所以。

下个版本会将其默认禁用，并在代码片段添加 CELL_DISPEL_EVOKER_CAUTERIZING_FLAME 变量，用于开启。
