### ISSUE TITLE
[Question]受难框体显示

### ISSUE THREAD

**Issue by shanluo911** [enderneko/Cell#81]
你好，请问现在可以支持显示受难框体吗？

**Comment by enderneko** [comment]
不可以，因为它们不是首领战中的友方NPC（指 unitid 为 bossX 的）。
简单地说，要显示它们只能通过匹配姓名版来显示，它们的 unitid 为 nameplateX。
但生成的框体是无法点击交互的（无法通过该框体选中、施放法术），这是 SecureUnitButtonTemplate / SecureActionButtonTemplate 的限制。（Enemy Grid 插件就是这么死的）
顺带一提，/cast [@nameplateX] xxx 这样的宏也是无效的。

综上，能做但Cell不考虑做，因为只能显示不能交互，不如用个WA。
