### ISSUE TITLE
虛影

### ISSUE THREAD

**Issue by class2u** [enderneko/Cell#82]
您好! 能否在 Cell 的框架中加入新詞綴的 虛影（繁中叫做 受苦的靈魂）的單位框架，以方便驅散，感謝!

![messageImage_1685679090109](https://github.com/enderneko/Cell/assets/420378/c8a73377-f8b4-4e8d-98f3-525ad184e539)

**Comment by enderneko** [comment]
嗯，我在r173版本的更新记录中回复了此请求。
这里我再简单说下吧，就是由于API的限制，这种功能是做不到的。
最多只能像WeakAuras那样，显示，但不能交互。
这对Cell来说没有意义，所以不考虑做。

**Comment by class2u** [comment]
了解，感謝!! <3
