### ISSUE TITLE
Performance issues WOTLK

### ISSUE THREAD

**Issue by erikbrgn** [enderneko/Cell#84]
Hello!

I really like this addon, thanks! However, I have quite a lot of issues when it comes to performance. Bigger groups (+25 people) causes stuttering and I'm not entirely sure what it could be. Perhaps a setting of some sort? I do not use `Increase Health Update Rate` and I've tried disabling smooth bar animation just in case, but the issue persists.

Any thoughts?

**Comment by enderneko** [comment]
I'm not really sure...
I heard LibHealComm may cause this kind of issue.
Also remember to check your WAs and damage meter addon, they usually use more CPU.

Some functions in Cell are not that CPU friendly.
Such as Buff Tracker, Death Report, AoE Healing.
And try not to create too many custom indicators.

**Comment by dss886** [comment]
try turn off “Death Check" and "Buff Tracker"
