### ISSUE TITLE
LUA ERRORS

### ISSUE THREAD

**Issue by codengyi** [enderneko/Cell#86]
3x Cell/RaidFrames/MainFrame.lua:283: attempt to call upvalue 'GetGroupMemberCountsForDisplay' (a nil value)
[string "@Cell/RaidFrames/MainFrame.lua"]:283: in function <Cell/RaidFrames/MainFrame.lua:282>
[string "@Cell/RaidFrames/MainFrame.lua"]:330: in function <Cell/RaidFrames/MainFrame.lua:322>
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetGroupMemberCountsForDisplay' (a nil value)"
GetGroupMemberCountsForDisplay = nil
L = <table> {
 Aura Icon Options = "효과 아이콘 옵션"
 Lines = "라인"
 Action = "동작"
 raidRosterTips = "[Right-Click] promote/demote (assistant). [Alt+Right-Click] uninvite."
 Glow Options = "반짝임 옵션"
 Health Bar Alpha = "생명력 바 투명도"
 hideFull = "전체 숨김"
 ALL = "모두"
 Debug Mode = "디버그 모드"
 Indicator settings are part of Layout settings which are account-wide. = "표시기 설정은 계정 전체 배치 설정의 일부입니다."
 Dispels = "해제 가능 디버프"
 Slash Commands = "슬래시 명령어"
 Alpha = "투명도"
 LEFT = "좌측"
 Extra Action Button = "추가 행동 버튼"
 Options UI Accent Color = "옵션 UI 강조 색상"
 Share = "공유"
 All Cell settings will be overwritten! = "모든 Cell 설정을 덮어씁니다!"
 Anchor Point = "고정 위치에서"
 stackFont = "Stack Font"
 GHOST = "유령"
 Click-Castings = "클릭-주문 시전"
 hideIfEmptyOrFull = "Hide while HP is empty/full"
 Battle Res Timer = "전투 준비 타이머 표시"
 Can't change options in combat = "전투 중 옵션을 바꿀 수 없습니다."
 Size = "크기"
 It will be renamed if this layout name already exists = "이 배치 이름이 이미 있는 경우 이름이 변경됩니다."
 bottom-to-top = "하단에서 상단으로"
 Font Outline = "글자 테두리"
 Layout = "배치"
 Icons = "아이콘들"
 Type:  = "유형:"
 Y Offset = "Y 간격"
 Font = "글자"
 Power Color = "자원 색상"
 Show Current Instance = "현재 인스턴스 표시"
 Frequency = "빈도"
 RAID_DEBUFFS_TIPS = "Tips: [Drag & Drop] to change debuff order. [Double-Click] on instance name to open Encounter Journal. [Shift+Left Click] on instance/boss name to share debuffs. [Alt+Left Click] on instance/boss name to reset debuffs. The priority of General Debuffs is higher than Boss Debuffs."
 Ready Check Icon = "준비 확인 아이콘"
 Yes = "예"
 My Nickname = "내 별명"
 Check if your group members need some raid buffs = "그룹 구성원에게 공격대 강화 효과가 필요한지 확인"
 Health Bar = "생명력 바"
 Raid Pets = "공격대 소환수"
 Debuff Type = "약화 효과 유형"
 BOTTOMLEFT = "좌측 하단"
 Vertical Gradient = "수직 그라데이션"
 Texture = "텍스처"
 Shield Bar = "보호막 바"
 Tip: Every layout has its own position setting = "팁: 모든 배치에는 자체 위치 설정이 있습니다."
 Monochrome Outline = "단색 테두리"
 Frame Level = "창 우선순위"
 Orientation = "방향"
 marksTips = "|r대상 표시기 왼쪽 클릭: |cffffffff대상에 공격대 표시기 설정|r 오른쪽 클릭: |cffffffff대상의 공격대 표시기 잠금 (나의 그룹)|r"
 C = "Class Talent"
 Hide Blizzard Party = "블리자드 파티 숨기기"
 TOPRIGHT = "우측 상단"
 circledStackNums = "Circled stack numbers"
 To show shield value, |cffff2727Glyph of Power Word: Shield|r is required = "To show shield value, |cffff2727Glyph of Power Word: Shield|r is required"
 Assist = "지원"
 Button4 = "4번 버튼"
 Current Profile = "현재 프로필"
 P = "PvP 특성"
 RESET = "Cell requires a full reset after updating from a very old version"
 Common = "공용"
 T = "특성"
 Cell will report first %d deaths during a raid encounter. = "Cell은 공격대 교전 중 처음 %d명의 죽음을 보고합니다."
 Bug Report & Suggestion = "버그 신고 & 제안"
 Arena = "투기장"
 PENDING = "대기"
 Indicator Settings = "표시기 설정"
 Hide Blizzard Frames = "블리자드 창 숨기기"
 Role Icon = "역할 아이콘"
 Boss Name = "우두머리 이름"
 TOP = "상단"
 Leader Icon = "파티장 아이콘"
 togglemenu_nocombat = "Menu (not in combat)"
 Heal Absorb = "치유 흡수"
 notBound = "|cff777777지정 안 됨"
 Aggro (border) = "어그로(테두리)"
 first %d = "처음 %d명"
 Import & Export All Settings = "모든 설정 가져오기 & 내보내기"
 Available slash commands = "사용 가능한 슬

**Comment by enderneko** [comment]
Weird, it should've been fixed.
I'll fix it again in next version.
Thanks for the feedback.
