### ISSUE TITLE
“指示器”和“副本减益”设置窗口会空白或无法选中

### ISSUE THREAD

**Issue by LeonNature** [enderneko/Cell#9]
1、在一次新建指示器的过程中，点击创建并输入指示器名称后点击“是”，插件失去了反应，随后再次点开指示器设置页面就无法选中任何词条、不能设置且已设置的指示器失效，重载、换号、重启游戏都不解决问题。（以上问题我在SavedVariables文件夹里的Cell.lua找到并删除了新增的那个指示器后已恢复正常，报告只为了提示可能存在的bug）

2、副本减益设置框也出现全部空白的情况，见图（正常点击对应版本应该会显示所有副本，随后可以自己选择副本添加监控技能）
![副本减益空白](https://user-images.githubusercontent.com/74559404/99287686-8bff9680-2875-11eb-8aa6-4273896215ab.png)

3、指示器可否设置法术ID，某些同名技能无法做到同时监控（如德鲁伊的塞纳里奥结界，在触发前和触发后是相同的中文名，但拥有不同的法术ID）

感谢作者的付出，我也非常喜欢CompactRaid，能在其基础上增添一些功能确实是非常棒的，支持。

**Comment by enderneko** [comment]
我在不同号上把每种指示器类型都新建了一遍，目前没能重现这个问题。
如果能提供报错代码那是极好的。

关于使用id判断的话，已经在做了的说。
感谢支持！

**Comment by LeonNature** [comment]
怎么查询错误代码？插件本身并没有报错。

我重现了指示器失效的状况，疑似在为指示器起名时使用了括号引起的
如图，点到指示器页签的任一实际指示器已经无法显示任何内容并选中了；或许副本减益空白也是类似问题？
![指示器失效](https://user-images.githubusercontent.com/74559404/99380128-7e452200-2904-11eb-91a9-3295c77143cb.png)

**Comment by enderneko** [comment]
你更新下版本试试？ 图里看你用的还是老版本哟

Sent from my iPhone

On Nov 17, 2020, at 18:42, LeonNature <notifications@github.com> wrote:

﻿

怎么查询错误代码？插件本身并没有报错。

我重现了指示器失效的状况，疑似在为指示器起名时使用了括号引起的
如图，点到指示器页签的任一实际指示器已经无法显示任何内容并选中了；或许副本减益空白也是类似问题？
[指示器失效]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F74559404%2F99380128-7e452200-2904-11eb-91a9-3295c77143cb.png&data=04%7C01%7C%7C610532b8f9504988c5a508d88ae57131%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637412065331819278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=I1OMPpDAWdAzvzw%2FecKqt%2B8tUUTpSKsJGMjYW6p35Ig%3D&reserved=0>

**Comment by LeonNature** [comment]
更新了可以了。。。谢谢老哥

话说有没有可能让大脚的单体插件同步更新你的版本？我是在大脚单体里搜compactraid的时候找到的你的插件，可以同步自动更新的话就更方便了，不然插件有了更新可能会不知道。

**Comment by enderneko** [comment]
大脚那边的话似乎是没有开放个人发布插件的功能，据我所知大脚插件站只相当于搬运curseforge、wowinterface等世界范围内主流插件站，所以个人没法主动更新，即使是原作者。

这种网站是方便了国内用户没错，但恕我直言，这和盗版没什么区别，因为它在转载时，插件的时候根本不会询问原作者的意愿。

**Comment by LeonNature** [comment]
对不起，作为用户没有考虑到这一层，将在curseforge上下载更新。
我会一直支持你的，那如果有更新能否做到在游戏内做个提示呢：）

**Comment by enderneko** [comment]
还好，现在大家的版权意识比以前好多了，这对于所有内容创作者都是好事儿。
我的话一直都用的curseforge的客户端，现在它们搬家到overwolf了，我觉得挺好用，你可以试试，NGA好像也有教程之类的。

至于更新提示是有的哦，触发条件是公会里有人装了这个插件，或者队伍里有，如果他的版本比你新，你就会收到提示。
但这个插件毕竟刚刚发布半个月，用的人还少呢，所以你只能多多关注发布页面啦，比如NGA的发布帖、GitHub、curseforge啦。

**Comment by LeonNature** [comment]
好的，感谢老哥
