### ISSUE TITLE
快捷施法无法和名字正确对应

### ISSUE THREAD

**Issue by zgshuguangzlj** [enderneko/Cell#91]
在使用职责顺序排位 如果随机本有人掉线以后 方框就无法和名字对应了  而且无法被修复
![QQ图片20231015075614](https://github.com/enderneko/Cell/assets/116779480/0a3dbab7-f61e-43d8-9ac4-3368bea66f6f)

**Comment by enderneko** [comment]
没明白你的意思，详细描述下。

另外，小队的排序方式不会影响快捷施法的顺序，这两者可以说没有关系。

**Comment by zgshuguangzlj** [comment]
正常情况下 格子和那个名字应该是一一对应的 名字应该是在快捷施法的格子正中间  但是我在随机本有队友掉线 T掉重新排进来一个人以后 名字和格子错开了
正常的是 NGA图片里那种一个萝卜一个坑的样式 我最开始在队友没掉线之前也是正常的 我现在的样式是我随邮件发来的图这样子的  [image:
QQ图片20231016123536.png]  名字和施法的格子错开了

KevinSK ***@***.***> 於 2023年10月16日 週一 上午6:32寫道：

**Comment by enderneko** [comment]
![Snipaste_2023-10-16_20-15-41](https://github.com/enderneko/Cell/assets/16433215/7ce5f055-d8d1-482f-83e3-a44222573721)
那很奇怪，设计的时候就没有将“名字显示在中间”作为有效选项。
因为中间要显示倒计时，刻意没有加这个“中间”的选项。

**Comment by zgshuguangzlj** [comment]
理解了 应该是我第一次打本的时候BUG了  反而这个错开是正常的  谢谢大大 晚安

KevinSK ***@***.***> 於 2023年10月16日 週一 下午8:17寫道：

**Comment by zgshuguangzlj** [comment]
> 在使用职责顺序排位 如果随机本有人掉线以后 方框就无法和名字对应了 而且无法被修复 ![QQ图片20231015075614](https://user-images.githubusercontent.com/116779480/275294565-0a3dbab7-f61e-43d8-9ac4-3368bea66f6f.png)
