### ISSUE TITLE
LUA after recent Wrath patch

### ISSUE THREAD

**Issue by volostyle** [enderneko/Cell#94]
Hi, I get this LUA error quite frequently since the latest Wrath patch came out:

7x [ADDON_ACTION_BLOCKED] AddOn 'Cell' tried to call the protected function 'CellRaidMarksFrame:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Show'
[string "@Cell/Widgets/Animation.lua"]:61: in function <Cell/Widgets/Animation.lua:57>
[string "@Cell/Widgets/Animation.lua"]:85: in function `FrameFadeIn'
[string "@Cell/Widgets/Animation.lua"]:113: in function <Cell/Widgets/Animation.lua:111>
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by enderneko** [comment]
Fixed.
