### ISSUE TITLE
Issues with Auto Spec Layout switch and Erroneous Buff indicators

### ISSUE THREAD

**Issue by Juts2** [enderneko/Cell#99]
Apologies for not capturing more info when it occurred. 

I ran into an issue after swapping between Preservation to Augmentation where the augmentation layout did not apply, but was showing as the active layout in the options panel. I had to reload UI to get the layout to update and indicators to change.

Upon changing back to Preservation, an erroneous Blistering Scales buff indicator was stuck on a player permanently until I reloaded the UI again. 

Version R205-Release

**Comment by enderneko** [comment]
well, it's difficult to locate the problem without lua error info.
tested, but no issues on my end.
can you reproduce this issue and take a screen recording?
